Icinga/icingaweb2

library/Icinga/Application/Hook.php

Fix module permissions for hooks

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php

Fix local timestamp for PostgreSQL queries

---

library/Icinga/Web/Widget/FilterEditor.php

FilterEditor: escape values correctly

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatehistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatehistoryQuery.php

Show check attempts only for soft state changes

---

library/Icinga/Authentication/User/DbUserBackend.php

DbUserBackend: don't fail at validation if there aren't any active users

---

doc/02-Installation.md

Change web2 mysql schema file location according to the setup module [config.ini](https://github.com/Icinga/icingaweb2/blob/master/packages/files/config/modules/setup/config.ini)

Update file path of icingaweb2 mysql schema for the manual installation procedure

---

modules/monitoring/application/forms/Command/Object/AcknowledgeProblemCommandForm.php

AcknowledgeProblemCommandForm: respect configuration when creating elements

---

modules/monitoring/application/views/scripts/show/components/downtime.phtml

Show every downtime's type in the detail view of a monitored object

---

application/clicommands/ModuleCommand.php

CLI: don't fail to disable an already disabled module

---

modules/monitoring/application/views/scripts/partials/command/object-command-form.phtml
modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php

Preserve quick actions in a command form view

---

modules/monitoring/application/views/scripts/list/servicegrid.phtml
test/php/library/Icinga/Data/Filter/FilterTest.php

Servicegrid: assemble filters with the Filter class

---

modules/monitoring/application/forms/Command/Object/AcknowledgeProblemCommandForm.php
modules/monitoring/application/forms/Command/Object/AddCommentCommandForm.php
modules/monitoring/application/forms/Command/Object/ScheduleServiceDowntimeCommandForm.php

Set focus to comment field for acknowledgements, downtimes and comments

---

library/Icinga/Application/ApplicationBootstrap.php
library/Icinga/Util/TimezoneDetect.php
test/php/library/Icinga/Util/TimezoneDetectTest.php

TimezoneDetect: support also negative timezone offsets

---

public/js/icinga/timer.js

Icinga.Timer: use setTimeout() instead of setInterval()

---

modules/monitoring/application/controllers/TimelineController.php

Timeline: fix link to acknowledgements

---

modules/monitoring/application/forms/Config/TransportConfigForm.php

Fix null->setDecorators()

---

library/Icinga/Cli/Command.php
library/Icinga/Cli/Documentation.php

Correct CLI help text for modules

---

doc/02-Installation.md

Also see:
* https://packages.icinga.com/epel/
* https://packages.icinga.com/fedora/

doc: Update Icinga repository release rpm location

---

application/forms/Config/General/LoggingConfigForm.php
library/Icinga/Application/Logger/Writer/PhpWriter.php

Emit log messages to the web server log

---

library/Icinga/Web/Controller.php
library/Icinga/Web/View.php

Enhance code autocompletion in IDEs

---

library/Icinga/Application/ClassLoader.php
modules/monitoring/library/Monitoring/Hook/DetailviewExtensionHook.php
modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php

Style monitored objects' detailview extensions as expected

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php

Adjust host severity

---

doc/20-Advanced-Topics.md

Docs: Add global URL parameters to advanced topics

---

library/Icinga/Web/View.php

Fix not working string[string] type hint in code docs

---

library/Icinga/Protocol/Ldap/Discovery.php

Suggest LDAP backend type based on the discovery (if any)

---

application/forms/Config/UserBackend/LdapBackendForm.php
modules/setup/application/forms/AuthBackendPage.php
modules/setup/library/Setup/WebWizard.php

Populate LdapBackendForm with suggestions only on the first access

---

application/forms/Config/UserBackend/LdapBackendForm.php
modules/setup/application/forms/AuthBackendPage.php

LdapBackendForm: move discoveries from createElements() to isValidPartial()

---

modules/setup/library/Setup/Steps/GeneralConfigStep.php

Fix error "Undefined index: logging_file"

---

modules/monitoring/library/Monitoring/Controller.php

Export CSV files with .csv extension

---

library/Icinga/Protocol/Ldap/Discovery.php
library/Icinga/Protocol/Ldap/LdapConnection.php
modules/setup/application/forms/LdapDiscoveryPage.php

Wizard: show LDAP connection settings discovery failure reasons

---

modules/monitoring/application/controllers/ListController.php
modules/monitoring/library/Monitoring/Controller.php

If anyone wants a more sophisticated fix I'll happily refactor our controller mess :grin: 
fixes #2967

Respect limits and sort orders for format requests

---

modules/doc/application/controllers/ModuleController.php

ModulesController: use setter for headers and response code

---

public/css/themes/solarized-dark.less

A dark theme based on [Solarized](http://ethanschoonover.com/solarized). HEX codes for colors are very similar [this guide](http://simianuprising.com/wp-content/uploads/2012/08/solarized-reference-horizontal.png). 
I've copied and modified `high-contrast.less` theme, some of the code might be still simplified.

Solarized dark theme

---

application/controllers/AnnouncementsController.php
library/Icinga/Web/Announcement/AnnouncementIniRepository.php

Sort announcements by date

---

application/clicommands/ModuleCommand.php
application/controllers/ConfigController.php
application/views/scripts/config/modules.phtml
library/Icinga/Application/Modules/Manager.php

Handle enabled, but deleted modules properly

---

.travis.yml
icingaweb2.ruleset.xml
library/Icinga/Exception/Http/BaseHttpException.php
library/Icinga/Exception/Http/HttpExceptionInterface.php
library/Icinga/Util/Json.php
library/Icinga/Web/Form.php
library/Icinga/Web/Response/JsonResponse.php
library/Icinga/Web/Widget/Chart/InlinePie.php
library/Icinga/Web/Widget/Tabs.php
modules/migrate/library/Migrate/Config/UserDomainMigration.php
modules/monitoring/application/clicommands/ListCommand.php
modules/monitoring/application/controllers/CommentController.php
modules/monitoring/application/forms/Config/TransportConfigForm.php
modules/monitoring/library/Monitoring/Command/Transport/ApiCommandTransport.php
modules/monitoring/library/Monitoring/Controller.php
modules/monitoring/library/Monitoring/Plugin/Perfdata.php
modules/setup/application/clicommands/ConfigCommand.php
modules/test/application/clicommands/PhpCommand.php
phpcs.xml
test/setup_vendor.sh

Enable PHP CodeSniffer in travis testing

---

application/forms/ConfigForm.php
test/php/library/Icinga/Web/ConfigFormTest.php

ConfigForm: transformEmptyValuesToNull does not handle values correctly

---

modules/monitoring/application/views/helpers/PluginOutput.php
modules/monitoring/public/css/module.less

In addition to OK, WARNING, CRITICAL and UNKNOWN detect UP and DOWN in plugin output to colorize it.

Detect UP and DOWN in plugin output to colorize output

---

library/Icinga/Application/ApplicationBootstrap.php

Implement ApplicationBootstrap::getStorageDir()

---

application/forms/Control/LimiterControlForm.php
application/forms/PreferenceForm.php
library/Icinga/Web/Controller.php

Add user preference for default number of items per page

---

modules/monitoring/application/forms/Config/TransportConfigForm.php
modules/monitoring/application/forms/Setup/TransportPage.php
modules/monitoring/library/Monitoring/MonitoringWizard.php
modules/setup/library/Setup/WebWizard.php

This fixes 2 issues:
@lippserd please have a look, especially on the TODOs left
fixes #3101

Wizard: Config validation button for Icinga 2 API

---

library/Icinga/Web/JavaScript.php
public/css/icinga/widgets.less
public/js/icinga/behavior/flyover.js

Implement togglable flyover

---

application/views/scripts/about/index.phtml

Requires translation refresh @lippserd

Update 'About' details with application name in version and corrected URLs

---

modules/doc/library/Doc/Renderer/DocSectionRenderer.php

DocSectionRenderer: trim trailing image url space

---

library/Icinga/Web/JavaScript.php
public/js/icinga/behavior/detach.js

Implement auto-detaching DOM elements

---

application/layouts/scripts/layout.phtml

layout: disable upload-iFrame for all but IE<10

---

library/Icinga/Data/Filter/Filter.php

Filter: new abstract methode and better IDE hints

---

library/Icinga/Chart/Donut.php
modules/monitoring/application/controllers/TacticalController.php
modules/monitoring/application/views/scripts/tactical/index.phtml
public/css/icinga/widgets.less

Redesign tactical overview

---

library/Icinga/Application/ApplicationBootstrap.php
library/Icinga/Application/Modules/Manager.php

Modules, Bootstrap: play nice with PHARs

---

application/layouts/scripts/parts/navigation.phtml
application/views/scripts/layout/menu.phtml
public/css/icinga/layout.less
public/css/icinga/menu.less
public/js/icinga/behavior/navigation.js
public/js/icinga/ui.js

Fixes #3132
Fixes #3150
Fixes #3152

Fix issues with new menu

---

application/layouts/scripts/layout.phtml
public/js/icinga/ui.js

js, layout: detect initial layout on load

---

library/Icinga/Chart/Donut.php

Fix float format of donut chart attributes

---

public/css/themes/Winter.less
public/css/themes/high-contrast.less
public/css/themes/solarized-dark.less

Update themes for 2.5.0

---

application/forms/Config/General/LoggingConfigForm.php

Syslog used to be the default selection. Now it's the webserver log.

setup: Don't show logging facility if webserver logging is selected

---

doc/02-Installation.md

icingacli is its own package on Debian and Ubuntu too.

Correct documentation about icingacli

---

library/Icinga/Web/Session/PhpSession.php

PhpSession: conform to PHP 7.1

---

public/js/icinga/ui.js

Don't discard fullscreen when detecting the layout

---

doc/80-Upgrading.md

Ported from the Icinga 2 docs.
fixes #3175

Docs: Enhance upgrade chapter with DB update instructions

---

library/Icinga/Application/Modules/Module.php

Don't require module.less

---

Vagrantfile

Vagrant: Use bento base box

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php

Fix filter by host custom variables

---

doc/20-Advanced-Topics.md

20-Advanced-Topics.de Fix typo

---

library/Icinga/Web/Navigation/Navigation.php

Fix unneccessary log message

---

.puppet/modules/php/manifests/init.pp
.puppet/modules/php/manifests/phpd.pp
.puppet/modules/scl/manifests/init.pp
.puppet/profiles/icingaweb2_dev/manifests/init.pp
.puppet/profiles/icingaweb2_dev/templates/icingaweb.conf.erb

Install PHP 7.1 from RedHat SCL

---

AUTHORS
library/Icinga/Authentication/UserGroup/LdapUserGroupBackend.php

Signed-off-by: Alexander A. Klimov <alexander.klimov@icinga.com>
refs #3250

Avoid including domain users in a group not belonging to a domain

---

modules/monitoring/application/forms/Config/SecurityConfigForm.php
modules/monitoring/application/locale/ar_SA/LC_MESSAGES/monitoring.po
modules/monitoring/application/locale/de_DE/LC_MESSAGES/monitoring.po
modules/monitoring/application/locale/it_IT/LC_MESSAGES/monitoring.po
modules/monitoring/application/locale/pt_BR/LC_MESSAGES/monitoring.po
modules/monitoring/application/locale/ru_RU/LC_MESSAGES/monitoring.po

Fix typo "existance"

---

library/Icinga/Application/Modules/Module.php

Hide inactive modules' config tabs

---

modules/monitoring/application/views/scripts/partials/object/host-header.phtml
modules/monitoring/application/views/scripts/partials/object/service-header.phtml

Remove leading and trailing blanks from ip addresses

---

public/js/icinga/events.js

Make search reset control working across auto-refresh

---

application/controllers/ApplicationStateController.php

/application-state: ignore unauthenticated requests

---

modules/monitoring/application/views/scripts/partials/object/detail-content.phtml
modules/monitoring/application/views/scripts/show/components/checksource.phtml
modules/monitoring/application/views/scripts/show/components/reachable.phtml

Separate reachability and check source info in detail views

---

doc/02-Installation.md

Installation doc: unify resulting installation on Debian and Ubuntu

---

modules/monitoring/application/controllers/ListController.php

Accept /monitoring/list/eventgrid?format=*

---

library/Icinga/Protocol/Ldap/LdapConnection.php
library/Icinga/Repository/Repository.php

LdapConnection: respect a query's limit as expected

---

application/forms/PreferenceForm.php

Handle missing Accept-Language header

---

doc/80-Upgrading.md

Upgrading doc: add breaking changes of 2.5

---

public/css/icinga/widgets.less

Don't display loading w/o JS

---

library/Icinga/Authentication/User/LdapUserBackend.php
library/Icinga/Authentication/UserGroup/LdapUserGroupBackend.php

Make multi-domain authn working w/ upper-case domains in user names

---

library/Icinga/Application/ApplicationBootstrap.php

Make icingacli working without the setup module

---

public/js/icinga/behavior/actiontable.js

Make navigation via browser history working as expected

---

public/css/icinga/widgets.less

Let wide dashlets scroll

---

modules/monitoring/application/views/helpers/PluginOutput.php

Branch has been renamed. Original pull request: #3272
fixes #2846

Transform escaped control characters in html plugin output

---

.puppet/modules/php/manifests/phpd.pp
.puppet/profiles/icingaweb2_dev/manifests/init.pp

Vagrant: fix missing PHP extensions

---

modules/monitoring/application/clicommands/ListCommand.php

Split icingacli monitoring list

---

modules/monitoring/doc/05-Command-Transports.md

Fix command transport documentation for inline comments

---

library/Icinga/Chart/Donut.php
modules/monitoring/application/controllers/TacticalController.php
public/css/icinga/widgets.less

Donut: place HTML tags outside <svg>

---

modules/doc/application/controllers/ModuleController.php

module/doc: End output buffering before serving module images

---

library/Icinga/Repository/Repository.php
library/Icinga/Util/ASN1.php
test/php/library/Icinga/Util/ASN1Test.php

Icinga\Repository::retrieveGeneralizedTime(): comply w/ RFC4517

---

doc/05-Authentication.md
doc/90-SELinux.md

@dgoetz Please review whether I've correctly included the necessary information.
fixes #3236

Add note about known optional SELinux booleans to the documentation

---

doc/80-Upgrading.md

Document that it's necessary to re-login after upgrading to 2.5.x

---

library/Icinga/File/Ini/IniParser.php

IniParser: include the file location in parsing exceptions

---

library/Icinga/Web/Helper/HtmlPurifier.php
library/Icinga/Web/Widget/Announcements.php
public/css/icinga/widgets.less

Render HTML in announcements' messages as expected

---

public/js/icinga/behavior/sparkline.js

Performance data: render pie charts without freezing the UI

---

application/forms/Config/UserGroup/UserGroupBackendForm.php
library/Icinga/Authentication/UserGroup/DbUserGroupBackend.php
library/Icinga/Authentication/UserGroup/LdapUserGroupBackend.php

UserGroupBackendForm: add button "Validate Configuration"

---

modules/monitoring/application/views/helpers/PluginOutput.php
modules/monitoring/library/Monitoring/Web/Helper/PluginOutputPurifier.php

Use new purifier helper for plugin output

---

application/views/scripts/iframe/index.phtml
public/css/icinga/main.less

Improve rendering of iframes in the dashboard

---

application/controllers/ErrorController.php
library/Icinga/Exception/IcingaException.php
modules/doc/library/Doc/Renderer/DocRenderer.php

Censor arguments in stack traces

---

application/controllers/ErrorController.php

Display messages of routing-time errors as expected

---

.puppet/profiles/icingaweb2_dev/manifests/init.pp

Vagrant: Fix package name for PHP xdebug in SCLO

---

library/Icinga/File/Pdf.php

Pdf: correct DOMPDF directory

---

library/Icinga/Application/Web.php

Unify the look of fatal and non-fatal errors

---

modules/monitoring/application/controllers/TacticalController.php

Mimics the behaviour of the ListController
Can output json and csv format via monitoring/tactical?format=json / monitoring/tactical?format=csv

TacticalController: Add OutputFormat json and csv

---

modules/monitoring/library/Monitoring/Command/Renderer/IcingaApiCommandRenderer.php

Send the correct 'force' attribute for 'check now' to the Icinga 2 API transport

---

public/css/icinga/responsive.less

Let a dashlet use the whole space if it's the only one

---

modules/monitoring/application/controllers/ListController.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupsummaryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupsummaryQuery.php
modules/monitoring/library/Monitoring/DataView/Hostgroupsummary.php
modules/monitoring/library/Monitoring/DataView/Servicegroupsummary.php

Make host and service groups sortable by the members' severities

---

application/forms/Navigation/NavigationItemForm.php

NavigationItemForm: Fix that urls with partial port macros are not saved

---

library/Icinga/File/Ini/IniParser.php

IniParser::parseIniFile(): parse as ::parseIni() would do

---

library/Icinga/Web/Widget/FilterEditor.php
public/css/icinga/widgets.less

FilterEditor: save changes on element addition

---

public/css/icinga/responsive.less

Fix header width for 4k resolutions.

---

public/js/icinga/behavior/sparkline.js

Revert "Performance data: render pie charts without freezing the UI"

---

application/controllers/DashboardController.php
application/views/scripts/dashboard/rename-pane.phtml
application/views/scripts/dashboard/settings.phtml
library/Icinga/Web/Widget/Dashboard/Pane.php

Fix that dashboard panes cannot be renamed

---

library/Icinga/Web/JavaScript.php
public/js/icinga/behavior/filtereditor.js
public/js/icinga/events.js

Preserve collapsed FilterEditor subtrees across auto-refreshes

---

public/js/icinga/loader.js

This reverts commit d1fd7e4be78f3dda9734027dda53114b71a7a46d.
Browsers seem to do this on their own natively. Way better.
refs #3348

Do not mangle cursor position in forms

---

modules/monitoring/application/views/scripts/show/contact.phtml
modules/monitoring/library/Monitoring/Backend/Ido/Query/ContactQuery.php

IDO: treat contacts of services of hosts as direct contacts of the hosts

---

public/js/icinga/events.js

500ms is for the average typist. Still fast enough, imho.
fixes #3348 (together with #3424)

Don't search as long as the user is typing

---

modules/monitoring/application/controllers/TacticalController.php
modules/monitoring/application/views/scripts/tactical/index.phtml

tactical: Allow to filter what is displayed

---

public/css/icinga/widgets.less
public/js/icinga/behavior/tooltip.js

tipsy: Don't use opacity but rgba to avoid having transparent text

---

modules/monitoring/library/Monitoring/Plugin/Perfdata.php
modules/monitoring/library/Monitoring/Plugin/ThresholdRange.php
modules/monitoring/test/php/library/Monitoring/Plugin/PerfdataTest.php
modules/monitoring/test/php/library/Monitoring/Plugin/ThresholdRangeTest.php

Interpret performance data threshold ranges

---

application/views/scripts/joystickPagination.phtml
modules/monitoring/application/controllers/ListController.php
modules/monitoring/application/views/scripts/list/servicegrid-flipped.phtml
modules/monitoring/application/views/scripts/list/servicegrid.phtml
modules/monitoring/public/css/service-grid.less

Flippable service grid axes

---

modules/doc/library/Doc/DocController.php

Doc: make PDF export action reachable

---

library/Icinga/Web/Controller/ActionController.php
library/Icinga/Web/Form.php
library/Icinga/Web/Form/Element/DateTimePicker.php
library/Icinga/Web/Request.php

Support creating announcements via API

---

modules/monitoring/library/Monitoring/Command/Renderer/IcingaApiCommandRenderer.php

Respect persistent when acknowledging over API

---

application/forms/Config/Resource/DbResourceForm.php
library/Icinga/Application/Platform.php
library/Icinga/Data/Db/DbConnection.php

Please review. I also removed the the unnessary offerSqlite. The provided code minds the code style from icingaweb2.
fixes #3381

Support SQLite resources

---

library/Icinga/Web/Request.php

Fix that Request parses json without respecting content type

---

modules/monitoring/application/clicommands/ListCommand.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php

Fix for CLI list --problems

---

application/controllers/ApplicationStateController.php
application/forms/AcknowledgeApplicationStateMessageForm.php
application/forms/Config/General/ApplicationConfigForm.php
application/forms/PreferenceForm.php
application/layouts/scripts/body.phtml
library/Icinga/Application/Hook/ApplicationStateHook.php
library/Icinga/Web/ApplicationStateCookie.php
library/Icinga/Web/Widget/ApplicationStateMessages.php
modules/monitoring/library/Monitoring/ProvidedHook/ApplicationState.php
public/css/icinga/widgets.less
public/js/icinga/behavior/application-state.js

Application state hook

---

modules/monitoring/run.php

monitoring: Introduce run.php and provide the new ApplicationStateHook

---

library/vendor/Zend/Db/Adapter/Pdo/Abstract.php

Pdo\Abstract: Properly handle incomplete error messages

---

modules/test/application/clicommands/PhpCommand.php
modules/test/phpunit.xml
test/php/bootstrap.php

icingacli test php unit: include the tests of all installed modules

---

modules/monitoring/application/views/scripts/show/components/grapher.phtml
modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php

Result using my PoC business process grapher:
fixes #3473

Make all grapher hooks available in the view

---

modules/monitoring/application/controllers/HostController.php
modules/monitoring/application/controllers/ListController.php
modules/monitoring/application/views/helpers/PluginOutput.php
modules/monitoring/application/views/scripts/list/hosts.phtml
modules/monitoring/application/views/scripts/list/services.phtml
modules/monitoring/application/views/scripts/show/components/output.phtml
modules/monitoring/doc/20-Hooks.md
modules/monitoring/library/Monitoring/Hook/PluginOutputHook.php
modules/monitoring/library/Monitoring/Web/Helper/PluginOutputHookRenderer.php

Introduce monitoring/PluginOutputHook

---

library/Icinga/Application/Web.php

This reverts commit b12b905076b1e566d7c9576689abe886b24f0a14, reversing
changes made to c633c86db727289a5c85270eddf3559065baf77f.
fixes #3500

Revert "Merge pull request #3487 from Icinga/fix/web-bootstrap"

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/ContactgroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcommentQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcommenthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcontactQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimeQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimestarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostflappingstarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostnotificationQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatehistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecommentQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecommenthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecontactQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimeQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimestarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServiceflappingstarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicenotificationQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatehistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php

Proper results when filtering for linked objects

---

doc/04-Resources.md

Add docs for timeout on LDAP resource

---

README.md
application/views/scripts/about/index.phtml
application/views/scripts/authentication/login.phtml
doc/02-Installation.md
doc/20-Advanced-Topics.md
doc/90-SELinux.md
library/vendor/Zend/README.md
modules/monitoring/doc/05-Command-Transports.md
public/error_unavailable.html

Update URL to https://icinga.com

---

modules/monitoring/application/views/helpers/PluginOutput.php

Fix extra spaces in command outputs after a comma

---

library/Icinga/Util/Format.php

Format::seconds(): handle negative values as expected

---

application/views/scripts/authentication/login.phtml

These url changes are all the result of following 301 redirects.

Use https:// links on login page

---

application/forms/ConfigForm.php
application/forms/Dashboard/DashletForm.php
library/Icinga/File/Ini/Dom/Section.php
library/Icinga/File/Ini/IniParser.php
test/php/library/Icinga/File/Ini/IniParserTest.php
test/php/library/Icinga/File/Ini/IniWriterTest.php

Fix escaped ini characters

---

modules/monitoring/application/controllers/EventController.php

Before this fix, the event detail view would always show the time in the servers timezone.

Fix that event detail view is not showing times in correct timezone

---

library/Icinga/Web/Navigation/NavigationItem.php
library/Icinga/Web/Navigation/Renderer/BadgeNavigationItemRenderer.php
library/Icinga/Web/Navigation/Renderer/NavigationItemRenderer.php
library/Icinga/Web/Navigation/Renderer/NavigationRenderer.php
library/Icinga/Web/Navigation/Renderer/NavigationRendererInterface.php
public/css/icinga/forms.less
public/css/icinga/menu.less
public/js/icinga/behavior/navigation.js
public/js/icinga/loader.js
public/js/icinga/ui.js

Fix collapsible sidebar issues

---

modules/monitoring/library/Monitoring/ProvidedHook/X509/Sni.php
modules/monitoring/run.php

Followup to https://github.com/Icinga/icingaweb2-module-x509/issues/1

Export hosts to the x509 module

---

library/Icinga/File/Ini/Dom/Directive.php
library/Icinga/File/Ini/IniParser.php
test/php/library/Icinga/File/Ini/IniParserTest.php
test/php/library/Icinga/File/Ini/IniWriterTest.php

Fix multiline values in ini files broken

---

modules/monitoring/doc/03-Configuration.md

Feel free to tell me if somethings requires adjustments like a better explanation of `PT1H`.

Add documentation for settings of the monitoring module

---

modules/monitoring/application/views/helpers/PluginOutput.php
modules/monitoring/test/php/application/views/helpers/PluginOutputTest.php

Preserve <br>s in plugin output

---

library/Icinga/Protocol/Ldap/LdapConnection.php

use the correct LDAPS port

---

modules/monitoring/application/controllers/HostsController.php
modules/monitoring/application/controllers/ServicesController.php
modules/monitoring/application/forms/Command/Object/CheckNowCommandForm.php
modules/monitoring/application/forms/Command/Object/ScheduleHostCheckCommandForm.php
modules/monitoring/application/forms/Command/Object/ScheduleServiceCheckCommandForm.php
modules/monitoring/application/views/scripts/hosts/show.phtml
modules/monitoring/application/views/scripts/services/show.phtml
modules/monitoring/configuration.php
modules/monitoring/doc/06-Security.md
modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php

Don't allow to reschedule checks for objects with no active checks

---

modules/monitoring/library/Monitoring/Controller.php

Filter::matchAny() without any subfilters matches none,
Filter::matchAll() without any subfilters matches all.

Monitoring\Controller#getRestriction(): return filters matching all, not none

---

modules/monitoring/library/Monitoring/Plugin/Perfdata.php

Allows for something like that:

Support temperatures (°C, °F) in perfdata

---

.puppet/modules/php/manifests/init.pp
.puppet/profiles/icingaweb2_dev/manifests/init.pp

Fix missing PHP-FPM restart after Puppet provisioning finished

---

modules/monitoring/application/views/scripts/list/hostgroup-grid.phtml
modules/monitoring/application/views/scripts/list/hostgroups.phtml
modules/monitoring/application/views/scripts/list/servicegroup-grid.phtml
modules/monitoring/application/views/scripts/list/servicegroups.phtml

Fix that the filter is not preserved when navigating away from the host-/servicegrid

---

doc/02-Installation.md
doc/20-Advanced-Topics.md
modules/setup/library/Setup/WebWizard.php

Setup: don't require date.timezone

---

modules/monitoring/application/controllers/EventController.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/StatechangeeventQuery.php
modules/monitoring/library/Monitoring/DataView/Statechangeevent.php

Add check source to history details view.

---

application/controllers/AnnouncementsController.php
application/forms/Announcement/AnnouncementForm.php
application/views/scripts/announcements/index.phtml
library/Icinga/Data/SimpleQuery.php
library/Icinga/Web/Announcement/AnnouncementIniRepository.php

Sortable announcements page

---

application/forms/Config/Resource/LdapResourceForm.php
library/Icinga/Protocol/Ldap/LdapConnection.php

Fix ldap connection fail with multiple servers

---

modules/monitoring/public/css/tables.less

CSS: Fix hover effect bug occuring in safari

---

library/Icinga/Util/Translator.php

Also adjust env var `LANGUAGE` when setting up the locale

---

public/css/icinga/layout.less
public/css/icinga/menu.less
public/css/icinga/responsive.less
public/js/icinga/ui.js

I improved the mobile menu a little.

Improve mobile menu

---

public/js/icinga/behavior/actiontable.js
public/js/icinga/events.js

Allow to fully customize click and submit handling

---

public/css/icinga/base.less
public/css/icinga/menu.less

Fix the indentation of level-2 nav-items

---

doc/06-Security.md
library/Icinga/User.php

Enable `$user:local_name$` placeholder in restrictions

---

application/layouts/scripts/layout.phtml

Option a) mentioned in issue.
resolves #2916

Support relative links with a base path

---

library/Icinga/Web/Url.php
modules/monitoring/library/Monitoring/Web/Navigation/Action.php

Fix object actions dont handle external paths properly

---

library/Icinga/Chart/Donut.php

Support higher number of problems in the tactical overview

---

application/forms/Announcement/AnnouncementForm.php

AnnouncementForm: Don't disable author field if it's an API request

---

library/Icinga/Web/Navigation/Renderer/BadgeNavigationItemRenderer.php
public/css/icinga/layout.less

ui: Show problem badges in collapsed sidebar

---

doc/03-Configuration.md

Document the logging config option 'php'

---

library/Icinga/Application/Hook.php
library/Icinga/Application/Modules/Module.php

Add possibility to disable permission checks for hooks

---

library/Icinga/Authentication/AuthChain.php

Send failed login-attempts to the audit log

---

application/controllers/AboutController.php
application/controllers/AccountController.php
application/controllers/AnnouncementsController.php
application/controllers/AuthenticationController.php
application/controllers/ConfigController.php
application/controllers/GroupController.php
application/controllers/ListController.php
application/controllers/NavigationController.php
application/controllers/RoleController.php
application/controllers/UserController.php
application/controllers/UsergroupbackendController.php
application/layouts/scripts/body.phtml
application/layouts/scripts/layout.phtml
library/Icinga/Web/Controller/ActionController.php
modules/monitoring/application/controllers/CommentController.php
modules/monitoring/application/controllers/CommentsController.php
modules/monitoring/application/controllers/ConfigController.php
modules/monitoring/application/controllers/DowntimeController.php
modules/monitoring/application/controllers/DowntimesController.php
modules/monitoring/application/controllers/EventController.php
modules/monitoring/application/controllers/HealthController.php
modules/monitoring/application/controllers/HostController.php
modules/monitoring/application/controllers/HostsController.php
modules/monitoring/application/controllers/ServiceController.php
modules/monitoring/application/controllers/ServicesController.php
modules/monitoring/application/controllers/ShowController.php
modules/monitoring/application/controllers/TacticalController.php
modules/setup/application/controllers/IndexController.php
public/js/icinga/loader.js

Fix wrong window title on some pages

---

library/Icinga/Cli/Command.php

CLI: Automatically load enabled modules if not disabled

---

library/Icinga/Date/DateFormatter.php
library/Icinga/Web/View/helpers/format.php
modules/monitoring/application/views/scripts/partials/downtime/downtime-header.phtml
modules/monitoring/application/views/scripts/show/components/downtime.phtml

Require time output for downtime schedule and end/expire times

---

public/js/icinga/behavior/navigation.js

navigation.js: Store and load sidebar collapse state from localStorage

---

modules/monitoring/application/controllers/HostController.php
modules/monitoring/application/controllers/ListController.php
modules/monitoring/application/views/scripts/list/hosts.phtml
modules/monitoring/application/views/scripts/list/services.phtml
modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php
modules/monitoring/public/css/tables.less

Make overdue/unreachable checks better visible

---

modules/monitoring/application/controllers/ListController.php
modules/monitoring/application/views/scripts/list/servicegrid.phtml
modules/monitoring/public/css/service-grid.less

Requires #3676 to work.
resolves #3793

Servicegrid: Add toggle to show problems only or everything

---

modules/monitoring/application/controllers/EventController.php
modules/monitoring/application/controllers/ListController.php
modules/monitoring/application/controllers/ShowController.php
modules/monitoring/application/views/scripts/list/contactgroups.phtml
modules/monitoring/application/views/scripts/list/contacts.phtml
modules/monitoring/application/views/scripts/list/notifications.phtml
modules/monitoring/application/views/scripts/list/services.phtml
modules/monitoring/application/views/scripts/partials/comment/comment-detail.phtml
modules/monitoring/application/views/scripts/partials/downtime/downtime-header.phtml
modules/monitoring/application/views/scripts/partials/event-history.phtml
modules/monitoring/application/views/scripts/partials/object/host-header.phtml
modules/monitoring/application/views/scripts/partials/object/service-header.phtml
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostnotificationQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/NotificationQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicenotificationQuery.php
modules/monitoring/public/css/module.less
modules/monitoring/public/css/tables.less

Improve host-service distinction in lists

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php
modules/monitoring/library/Monitoring/DataView/Hostgroupsummary.php
modules/monitoring/library/Monitoring/DataView/Hoststatus.php
modules/monitoring/library/Monitoring/DataView/Servicegroupsummary.php
modules/monitoring/library/Monitoring/DataView/Servicestatus.php

Add contact and contactgroup filters

---

public/css/icinga/login.less
public/css/icinga/responsive.less

Fix bad looking login form errors

---

public/css/themes/high-contrast.less

Improve high contrast theme readability

---

library/Icinga/Data/Db/DbQuery.php

Support wildcard filters in chains

---

library/Icinga/Data/Db/DbQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php

Fix flawed group filter chains

---

public/css/icinga/login.less

Center inputs in loginform

---

modules/monitoring/application/views/scripts/partials/comment/comment-detail.phtml
modules/monitoring/application/views/scripts/partials/downtime/downtime-header.phtml

Restore multiselection for downtimes and comments

---

public/js/icinga/loader.js
public/js/icinga/ui.js

Asynchronous Content Updates

---

modules/monitoring/application/controllers/TimelineController.php
modules/monitoring/library/Monitoring/Timeline/TimeLine.php
modules/monitoring/public/css/module.less

* Fixes extrapolation style
* Fixes missing notifications
fixes #3947

Fix timeline

---

modules/monitoring/library/Monitoring/DataView/Hostgroupsummary.php
modules/monitoring/library/Monitoring/DataView/Servicegroupsummary.php

Fix invalid filter suggestions in group overviews

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php

Fix checks being marked as late when they are scheduled for later time

---

modules/monitoring/application/controllers/EventController.php

Render missing dates of event details

---

library/Icinga/Data/SimpleQuery.php
modules/monitoring/application/views/scripts/partials/event-history.phtml
modules/monitoring/library/Monitoring/Backend/Ido/Query/EmptyhostgroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/EmptyservicegroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupsummaryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupsummaryQuery.php

Fixes the performance issues and provides an alternative for #3836.
fixes #3928

Enhance query performance when filtering for groups and reduce double query execution

---

library/Icinga/User.php
modules/monitoring/application/controllers/ListController.php
modules/monitoring/application/controllers/ShowController.php
modules/monitoring/application/views/scripts/partials/object/detail-content.phtml
modules/monitoring/configuration.php
modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php

New permission `no-monitoring/contacts`

---

application/controllers/AccountController.php
application/forms/Security/RoleForm.php

New permission `no-user/password-change`

---

application/views/scripts/navigation/dashboard.phtml
library/Icinga/Authentication/User/ExternalBackend.php

Fix external authentication

---

modules/monitoring/application/controllers/HostsController.php
modules/monitoring/application/controllers/ServicesController.php

hosts/services: Remove `*_active_checks_enabled` from a redirect's filter

---

library/Icinga/Web/View/Helper/IcingaCheckbox.php
public/css/icinga/forms.less

Make toggle sliders accessible

---

application/forms/Security/RoleForm.php

Assist browsers in breaking permission and restriction labels onto multiple lines

---

modules/monitoring/configuration.php

Also consider normal acknowledgements for acknowledged problems

---

library/Icinga/Data/Filter/FilterQueryString.php

Numbers in filter conditions not interpreted correctly

---

modules/monitoring/application/forms/Config/SecurityConfigForm.php
modules/monitoring/library/Monitoring/Object/MonitoredObject.php

Reverts Icinga/icingaweb2#3993

Revert "Introduce option to hide specific customvars in web"

---

public/js/icinga/loader.js

Enable the possibility to refresh the parent container of the given element passed through X-Icinga-Extra-Updates http-header.

Refresh container if X-Icinga-Extra-Updates with length 1 is defined

---

doc/20-Advanced-Topics.md

Added Kiosk Mode description, based on customer wish ref/NC/19457 & ref/NC/19599

Added Kiosk Mode in doc

---

public/css/icinga/forms.less

css: Remove left-right padding from inline form elements

---

application/forms/Config/ResourceConfigForm.php
application/forms/Config/UserBackendConfigForm.php
application/forms/Config/UserGroup/UserGroupBackendForm.php
library/Icinga/Protocol/Ldap/LdapConnection.php

Fix error on incomplete ldap inspection

---

public/js/icinga/loader.js

Make sure that class container has its container

---

public/js/icinga/behavior/navigation.js

fix unexpected flyout delay

---

public/css/themes/colorblind.less

https://github.com/Icinga/icingaweb2/issues/4066
Changed text colour to black as it was difficult to read.
Hope you have a nice day! (First contribution BTW <3)

colorblind.less: Add contrast to text with light background

---

public/css/icinga/layout-structure.less

Fix flyouts overlapped by main content

---

library/Icinga/Application/Modules/Module.php

Don't fail with an exception if module.info is flawed

---

modules/monitoring/application/controllers/TacticalController.php

Fix tactical overview misinterpreting environment

---

doc/02-Installation.md

Docs: include Ubuntu in "Preparing Web Setup on Debian"

---

modules/monitoring/application/views/scripts/show/components/customvars.phtml

Show customvar names as-is

---

modules/monitoring/library/Monitoring/Object/Macro.php

Also resolve macro `service.name` in notes_url

---

modules/monitoring/application/views/helpers/PluginOutput.php

Adjust html detection in plugin output (again)

---

modules/monitoring/application/forms/Command/Object/DeleteCommentCommandForm.php
modules/monitoring/application/forms/Command/Object/DeleteCommentsCommandForm.php
modules/monitoring/application/forms/Command/Object/DeleteDowntimeCommandForm.php
modules/monitoring/application/forms/Command/Object/DeleteDowntimesCommandForm.php
modules/monitoring/application/forms/Command/Object/RemoveAcknowledgementCommandForm.php
modules/monitoring/library/Monitoring/Command/Object/CommandAuthor.php
modules/monitoring/library/Monitoring/Command/Object/DeleteCommentCommand.php
modules/monitoring/library/Monitoring/Command/Object/DeleteDowntimeCommand.php
modules/monitoring/library/Monitoring/Command/Object/RemoveAcknowledgementCommand.php
modules/monitoring/library/Monitoring/Command/Object/WithCommentCommand.php
modules/monitoring/library/Monitoring/Command/Renderer/IcingaApiCommandRenderer.php

Transmit author when removing downtimes comments and acks

---

public/css/icinga/modal.less

Make modals responsive

---

CHANGELOG.md
doc/80-Upgrading.md

Add missing upgrade docs

---

public/js/icinga/utils.js

js: Properly parse/build url query values

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php

Fix case insensitive membership filters on Postgres

---

application/forms/Config/User/UserForm.php
application/forms/Config/UserGroup/UserGroupForm.php

Adding the ConfigFormEventsHook to UserForm and UserGroupForm, we give the possibility to handle the User/UserGroup creation/update/delete action and as a consequence trigger dedicated actions based on this change (for example log them).

Add ConfigFormEventsHook to UserForm and UserGroupForm

---

modules/monitoring/application/controllers/TacticalController.php
modules/monitoring/application/views/scripts/tactical/index.phtml

/monitoring/tactical: don't show negative amounts of monitored objects

---

public/css/icinga/responsive.less

Show overflowing content in the sidebar while in minimal layout

---

library/Icinga/Data/Db/DbQuery.php

Fix timestamp filters in history views

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php

Fix single negated membership filters with PostgreSQL

---

application/controllers/StaticController.php

static/img: Make sure to correctly access module images

---

modules/monitoring/application/controllers/CommentController.php
modules/monitoring/application/controllers/DowntimeController.php
modules/monitoring/application/controllers/EventController.php
modules/monitoring/application/views/scripts/comment/show.phtml
modules/monitoring/application/views/scripts/downtime/show.phtml

Use TicketHook where missing

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php

list/services: Avoid duplicates when filtering contact(group)s

---

modules/monitoring/library/Monitoring/Web/Navigation/Action.php

Don't try to resolve macros in non existing action urls

---

application/forms/PreferenceForm.php
library/Icinga/Web/Controller.php

Fix zero page limit loads everything

---

public/css/icinga/menu.less

Fix color shifts in state summary badges

---

library/Icinga/Web/Url.php

Url::fromPath(): var_export() input value to complain about

---

.puppet/profiles/icingaweb2_dev/files/modules/monitoring/commandtransports.ini
.puppet/profiles/icingaweb2_dev/manifests/init.pp

... not to have to configure it every time.

Vagrant: provide .../monitoring/commandtransports.ini

---

application/controllers/ApplicationStateController.php
application/forms/PreferenceForm.php
library/Icinga/Web/Controller/ActionController.php

Make auto refresh interval configurable

---

modules/monitoring/application/forms/Command/Object/AddCommentCommandForm.php
modules/monitoring/application/views/scripts/show/components/comments.phtml
modules/monitoring/doc/03-Configuration.md
modules/monitoring/library/Monitoring/Command/Object/AddCommentCommand.php
modules/monitoring/library/Monitoring/Command/Renderer/IcingaApiCommandRenderer.php

Monitoring: add expire option for comments

---

library/Icinga/Application/Modules/Module.php

Don't emit warnings for module assets

---

library/Icinga/Web/LessCompiler.php

Using the following in a module's less file:
```
@exports: {
@foo: "bar";
@number: 4;
@color: red;
};
```
will export the variables `@foo`, `@number` and `@color` into the global scope.
Though, exports are not able to override already defined variables.
That's still reserved for themes.
refs #4271

Add support for LESS variable exports by modules

---

application/forms/Security/RoleForm.php

Preserve previous settings for admin roles

---

modules/monitoring/application/forms/Command/Object/DeleteDowntimeCommandForm.php

Show error notification if downtime removal is not successful

---

modules/monitoring/application/views/helpers/PluginOutput.php
modules/monitoring/test/php/application/views/helpers/PluginOutputTest.php

Fix that subsequent escaped newlines are not transformed in plugin output

---

application/controllers/AccountController.php
application/forms/Config/General/ApplicationConfigForm.php
application/forms/Config/GeneralConfigForm.php
library/Icinga/Authentication/Auth.php
library/Icinga/Common/Database.php
library/Icinga/User/Preferences/PreferencesStore.php
modules/setup/library/Setup/Requirement/SetRequirement.php
modules/setup/library/Setup/WebWizard.php

Enforce database as configuration backend

---

library/Icinga/Authentication/UserGroup/LdapUserGroupBackend.php
library/Icinga/Protocol/Ldap/LdapQuery.php

Fix handling of multi valued ldap attributes

---

library/Icinga/Data/Db/DbConnection.php
library/Icinga/Data/Db/DbQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php

This comes from https://github.com/Icinga/ipl-sql/pull/31

Transform `*` equal/unequal comparisons to NULL checks

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php

Accept any character in custom var names

---

public/js/icinga/loader.js

Fix that GET forms don't update the history upon autosubmit

---

doc/20-Advanced-Topics.md

Provides consistency with the 853bbf2 update.

Docs: Fix automatic install password hash command

---

library/Icinga/Data/DataArray/ArrayDatasource.php
test/php/library/Icinga/Data/DataArray/ArrayDatasourceTest.php

Fix incorrect `ArrayDatasource` order with limit and offset applied

---

modules/monitoring/library/Monitoring/Plugin/Perfdata.php

Don't render missing perfdata values as `0.00`

---

modules/monitoring/library/Monitoring/MonitoringWizard.php
modules/setup/library/Setup/WebWizard.php

setup: Skip browser validation when validating a form manually

---

doc/02-Installation.md

name for the powertools changed to lowercase

fixed powertools repo name for CentOS 8

---

doc/02-Installation.md

doc: Add a note about browser support in the install section

---

application/controllers/HealthController.php
library/Icinga/Application/Hook/HealthHook.php
library/Icinga/Web/Menu.php
library/Icinga/Web/Navigation/Renderer/HealthNavigationRenderer.php
library/Icinga/Web/StyleSheet.php
library/Icinga/Web/View/AppHealth.php
modules/monitoring/library/Monitoring/ProvidedHook/Health.php
modules/monitoring/run.php
public/css/icinga/health.less

```json
{
"status": "success",
"data": [
{
"module": "icingadb",
"name": "Icinga DB",
"url": "/icingaweb2/icingadb/health",
"state": 0,
"message": "Icinga DB is running and writing into the database",
"metrics": {
"heartbeat": 1620999868.801,
"responsible": true,
"icinga2_active_host_checks_enabled": true,
"icinga2_active_service_checks_enabled": true,
"icinga2_event_handlers_enabled": true,
"icinga2_flap_detection_enabled": true,
"icinga2_notifications_enabled": true,
"icinga2_performance_data_enabled": true,
"icinga2_start_time": 1620998.773,
"icinga2_version": "r2.12.0-1",
"endpoint": {
"name": "docker-master"
}
}
},
{
"module": "icingadb",
"name": "Icinga Redis",
"url": null,
"state": 0,
"message": "Icinga Redis available and up to date.",
"metrics": {}
},
{
"module": "monitoring", …
```

Health endpoint

---

application/forms/PreferenceForm.php
application/layouts/scripts/layout.phtml
application/views/helpers/FormDateTime.php
library/Icinga/Authentication/Auth.php
library/Icinga/Web/JavaScript.php
public/css/icinga/modal.less
public/css/themes/solarized-dark.less
public/js/define.js
public/js/icinga/behavior/datetime-picker.js
public/js/icinga/behavior/modal.js

**Default style with default locale in the monitoring module**
**Default style with default locale in Icinga DB Web**
**Dark style with german locale in Icinga DB Web**
blocked by https://github.com/Icinga/ipl-web/pull/15
resolves #4107
refs #3416

Add datetime picker widget

---

application/forms/Config/UserBackendConfigForm.php
library/Icinga/Authentication/User/UserBackend.php
library/Icinga/Authentication/User/UserBackendInterface.php
test/php/application/forms/Config/UserBackendReorderFormTest.php

refs #2840
refs #4365
This is a re-submit of #4365 with maintainer edits enabled

Make configuration of custom user backends possible

---

application/forms/Config/UserGroup/UserGroupBackendForm.php
library/Icinga/Authentication/UserGroup/UserGroupBackend.php
library/Icinga/Authentication/UserGroup/UserGroupBackendInterface.php

Make configuration of custom user-group backends possible

---

library/Icinga/Web/View/AppHealth.php
library/Icinga/Web/View/PrivilegeAudit.php
library/Icinga/Web/Widget/SingleValueSearchControl.php

Requires https://github.com/Icinga/ipl-html/pull/51

Use strict ipl-html interfaces

---

modules/doc/public/css/module.less
modules/monitoring/public/css/module.less
modules/monitoring/public/css/service-grid.less
modules/monitoring/public/css/tables.less
public/css/icinga/about.less
public/css/icinga/audit.less
public/css/icinga/base.less
public/css/icinga/controls.less
public/css/icinga/forms.less
public/css/icinga/health.less
public/css/icinga/layout.less
public/css/icinga/login.less
public/css/icinga/main.less
public/css/icinga/menu.less
public/css/icinga/mixins.less
public/css/icinga/setup.less
public/css/icinga/widgets.less

Respect yet unused CSS variables as well

---

doc/06-Security.md
doc/80-Upgrading.md
library/Icinga/Authentication/AdmissionLoader.php
library/Icinga/Web/Navigation/NavigationItem.php

Support $user.local_name$ macro in navigation items

---

public/css/icinga/compat.less

CSS: Fix `th` background in dashboard settings

---

public/css/icinga/base.less
public/css/icinga/compat.less
public/css/icinga/menu.less
public/css/themes/Winter.less
public/css/themes/high-contrast.less
public/css/themes/solarized-dark.less

fixes #4413
Note to myself: Cherry-pick the theme commits into `disable-dark-theme`

Fix menu hover colors

---

application/controllers/ConfigController.php
library/Icinga/Web/Response.php
public/js/icinga/loader.js

Fix that the right column is lost when enabling a module

---

application/views/scripts/navigation/dashboard.phtml
public/css/icinga/widgets.less

Dashboard: Add ability to use IPL Icons

---

public/css/icinga/widgets.less

CSS: Make labels wrap in Safari

---

modules/monitoring/application/controllers/ListController.php

monitoring/list/*: Don't apply restrictions in case of `?format=sql`

---

modules/monitoring/library/Monitoring/Object/MonitoredObject.php

Keep structure of nested cvs during protection

---

application/controllers/UserController.php

user/createmembership: Don't render `user/form.phtml`

---

library/Icinga/Web/Helper/Markdown/LinkTransformer.php

Don't open external urls in comments in iFrames

---

library/Icinga/Common/Database.php

Only use `PDO::MYSQL_ATTR_INIT_COMMAND` for mysql connections

---

doc/02-Installation.md
modules/setup/library/Setup/WebWizard.php

Fix oudated install requirements

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php

Define correct grouping rules for contacts and -groups

---

modules/setup/library/Setup/WebWizard.php

Ensure to properly setup table `icingaweb_rememberme` in the wizard

---

public/js/icinga/behavior/datetime-picker.js

Fix that the datetime picker doesn't close automatically

---

library/Icinga/Chart/SVGRenderer.php

Let SVG chart library process input as UTF-8

---

doc/80-Upgrading.md
modules/migrate/application/clicommands/PreferencesCommand.php

Add preference migration command

---

library/Icinga/Authentication/User/UserBackend.php
library/Icinga/Authentication/UserGroup/UserGroupBackend.php
library/Icinga/Common/Database.php
library/Icinga/User/Preferences/PreferencesStore.php
modules/migrate/application/clicommands/PreferencesCommand.php
modules/migrate/library/Migrate/Config/UserDomainMigration.php

Enforce charset on internal db queries

---

library/Icinga/Authentication/User/UserBackend.php
library/Icinga/Authentication/UserGroup/UserGroupBackend.php
library/Icinga/Common/Database.php
library/Icinga/User/Preferences/PreferencesStore.php
modules/migrate/application/clicommands/PreferencesCommand.php
modules/migrate/library/Migrate/Config/UserDomainMigration.php

If enforcing a charset, DO IT ONLY IF THE DB TYPE IS CORRECT

---

application/controllers/AuthenticationController.php
library/Icinga/Crypt/AesCrypt.php
library/Icinga/Web/RememberMe.php

Utilize multiple encryption ciphers for remember me

---

modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php

IdoQuery: Qualify and resolve subquery filters ASAP

---

public/js/icinga/behavior/modal.js

Fix multi modal windows and submit

---

public/css/icinga/widgets.less

CSS: Adjust application state summary notification design

---

modules/monitoring/application/views/helpers/PluginOutput.php
modules/monitoring/test/php/application/views/helpers/PluginOutputTest.php

PluginOutput: Don't "optimize" two subsequent newlines to one

---

application/forms/PreferenceForm.php
library/Icinga/Web/StyleSheet.php

Fix missing themes cause errors

---

modules/migrate/application/clicommands/NavigationCommand.php

Migrate: Add possibility to migrate monitoring navigation items

---

application/views/scripts/error/error.phtml

Error: Add missing `</div>` for `.content` element

---

public/js/icinga/loader.js

fixes #4598
fixes #4604
fixes Icinga/icingaweb2-module-director#2427

js: Fix that redirects into currently empty columns don't work

---

modules/setup/application/forms/LdapDiscoveryPage.php

Fix TypeError when skipping ldap in setup wizard

---

.puppet/profiles/icingaweb2_dev/templates/config.ini.erb

Before:
* Remember me checkbox was disabled
* Preferences form called a method on null on submission

Vagrant: Puppet: Icinga Web 2: set config database

---

modules/migrate/application/clicommands/NavigationCommand.php

Fix migrating navigation items only for the given user doesn't work

---

application/forms/Security/RoleForm.php

RoleForm: Really only show that everything is allowed if `*` is granted

---

library/Icinga/Chart/Donut.php
modules/monitoring/application/controllers/TacticalController.php
public/css/icinga/widgets.less

/monitoring/tactical: fall back to unknown services if none critical

---

test/php/library/Icinga/File/Storage/TemporaryLocalFileStorageTest.php

tests: Introduce `TemporaryLocalFileStorageTest`

---

library/Icinga/Web/Helper/Markdown/LinkTransformer.php

Do not load any user links in iframes

---

library/Icinga/Application/Modules/Manager.php
library/Icinga/Application/Modules/Module.php

Fix module dependency evaluation

---

library/Icinga/Web/Form.php
library/Icinga/Web/Form/Element/CsrfCounterMeasure.php
modules/monitoring/application/views/scripts/partials/object/quick-actions.phtml
public/js/icinga/utils.js

Fix duplicate ids in html

---

public/js/icinga/ui.js

Properly reset container ids when moving content

---

modules/monitoring/application/views/scripts/show/components/comments.phtml
public/css/icinga/main.less

Fix ghost columns upon comment removal

---

modules/monitoring/application/controllers/ListController.php

monitoring/list/hosts: Apply restrictions to host service problem summary

---

library/Icinga/Data/Db/DbQuery.php

The timezone in the screenshot is `Europe/Berlin` (Winter +01:00, Summer +02:00)
fixes #4568

Fix that daylight savings are not accounted for in queries

---

public/css/themes/Winter.less

Winter.less: Update styles

---

public/css/icinga/layout-structure.less

Fix that the sidebar shadow narrows the interaction area

---

modules/monitoring/library/Monitoring/Plugin/Perfdata.php

Fixes https://github.com/Icinga/icinga2/issues/9206

Perfdata: Render unknown UOMs as-is

---

modules/monitoring/application/views/helpers/PluginOutput.php
modules/monitoring/test/php/application/views/helpers/PluginOutputTest.php

Fix newline characters in HTML plugin output

---

application/controllers/HealthController.php

refs https://github.com/Icinga/ipl-web/pull/72

Adjust calls to CompatController::setTitle()

---

modules/monitoring/application/views/scripts/partials/object/quick-actions.phtml

Fix broken check now quick actions

---

modules/monitoring/application/controllers/TacticalController.php

Use correct link for the unknown services counter in the tactical overview

---

public/js/icinga/behavior/actiontable.js

Restore mouseover for list items on the dashboard

---

public/css/icinga/base.less

CSS: Improve sidebar contrast

---

application/forms/PreferenceForm.php

PreferenceForm: Always enable mode selection if user theme is compatible

---

doc/80-Upgrading.md
etc/schema/mysql-upgrades/2.11.0.sql
etc/schema/mysql.schema.sql
library/Icinga/Authentication/User/DbUserBackend.php
library/Icinga/Authentication/User/UserBackend.php
library/Icinga/Authentication/UserGroup/DbUserGroupBackend.php
library/Icinga/Authentication/UserGroup/UserGroupBackend.php
library/Icinga/User/Preferences/PreferencesStore.php
modules/migrate/application/clicommands/PreferencesCommand.php
modules/migrate/library/Migrate/Config/UserDomainMigration.php

sql: Change charset to `utf8mb4`

---

modules/setup/application/views/scripts/index/index.phtml
modules/setup/library/Setup/RequirementSet.php

Fix setup wizard

---

library/Icinga/Application/Modules/Manager.php

Manager: Ensure enableModule dir has correct permission when created

---

library/Icinga/Data/Db/DbConnection.php

DbConnection: Only ignore the `*` for equal/unequal conditions

---

application/controllers/RoleController.php

Fix that the audit view doesn't suggest users from domain-aware backends correctly

---

library/Icinga/Web/StyleSheet.php

(cherry picked from commit c65ba3c2fc765119fa1753d1accff0c9a1c5072a)

Stylesheet: Don't parse library CSS as LESS

---

library/Icinga/Web/Navigation/ConfigMenu.php

ConfigMenu: Add missing application_log entry

---

library/Icinga/Web/Navigation/ConfigMenu.php
public/js/icinga/behavior/navigation.js

Fix that the new user menu forgets active states

---

library/Icinga/Less/Call.php
library/Icinga/Less/ColorProp.php
library/Icinga/Less/ColorPropOrVariable.php
library/Icinga/Less/DeferredColorProp.php
library/Icinga/Less/LightMode.php
library/Icinga/Less/LightModeCall.php
library/Icinga/Less/LightModeDefinition.php
library/Icinga/Less/LightModeTrait.php
library/Icinga/Less/LightModeVisitor.php
library/Icinga/Less/Visitor.php
test/php/library/Icinga/Util/LessParserTest.php

Fix light mode variable references resolution issue

---

etc/schema/mysql-upgrades/2.11.0.sql
etc/schema/mysql.schema.sql
etc/schema/pgsql-upgrades/2.11.0.sql
etc/schema/pgsql.schema.sql

Introduce schema table

---

library/Icinga/Data/Db/DbQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcommentdeletionhistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcommenthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimeendhistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimestarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostflappingstarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostnotificationQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatehistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecommentdeletionhistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecommenthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimeendhistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimestarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServiceflappingstarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicenotificationQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatehistoryQuery.php

Fix incorrect history time and date

---

library/Icinga/Util/Format.php

refs https://github.com/Icinga/icingadb-web/issues/586

Format.php: Handle null values

---

public/css/icinga/mixins.less

Align button icon to baseline

---

public/css/icinga/setup.less

setup.less: Make visible that the button is disabled

---

modules/monitoring/library/Monitoring/Object/Macro.php

Macro: Log the object where a macro is not found

---

application/forms/Security/RoleForm.php
library/Icinga/Web/View/PrivilegeAudit.php
modules/monitoring/public/css/module.less
public/css/icinga/audit.less
public/css/icinga/base.less
public/css/icinga/main.less
public/css/icinga/widgets.less
public/js/icinga/behavior/collapsible.js
public/js/icinga/utils.js

Enhance collapsible js

---

library/Icinga/File/Csv.php

Fix missing escape of double quotes in CSV output.

---

application/controllers/AuthenticationController.php
application/forms/Authentication/LoginForm.php

login: Don't redirect to external resources

---

application/controllers/RoleController.php

RoleController: Always perform a permission check

---

library/Icinga/Web/Form/Validator/InternalUrlValidator.php

Such as `data:...`
fixes #4959

External URLs still allowed in dashlets

---

library/Icinga/Web/Navigation/ConfigMenu.php

ConfigMenu: Fix incorrect shared navigation url

---

modules/test/application/clicommands/PhpCommand.php

so that GHA knows if something failed.

icingacli test php unit: pass through phpunit exit code

---

library/Icinga/Web/Form/Validator/InternalUrlValidator.php

Check if url is external in validation function

---

public/js/icinga/loader.js

This header contains the name of the element responsible for triggering the automatic form submission.

js: Transmit `X-Icinga-AutoSubmittedBy` upon autosubmits

---

application/views/scripts/form/reorder-authbackend.phtml
modules/monitoring/application/views/scripts/form/reorder-command-transports.phtml
modules/setup/application/views/scripts/form/setup-modules.phtml
modules/setup/application/views/scripts/form/setup-requirements.phtml
modules/setup/application/views/scripts/form/setup-summary.phtml

Fix some reflected XSS bugs

---

library/Icinga/File/Storage/TemporaryLocalFileStorage.php

TemporaryLocalFileStorage: Fix unexpected crash in destructor

---

application/forms/Config/General/LoggingConfigForm.php
modules/setup/application/views/scripts/form/setup-welcome.phtml

to make that patch obsolete.
CC @julianbrost FYI

Provide the behaviour the Docker images patch into us by ourselves

---

public/js/icinga/behavior/modal.js
public/js/icinga/events.js

Allows other listeners to also react to automatic submissions of forms.

Let autosubmits trigger real submits

---

.github/workflows/docker.yml

* Icinga/docker-icingaweb2#109

GHA: handle changed interface of Icinga/docker-icingaweb2

---

public/css/icinga/base.less

base.less: Make menu nav-level-2 hover better visible

---

library/Icinga/Web/JavaScript.php
public/js/icinga/behavior/copy-to-clipboard.js

Utilizes `CopyToClipboard.js` from ipl-web
Blocked by https://github.com/Icinga/ipl-web/pull/151
ref: https://github.com/Icinga/icingadb-web/issues/677

Javascript: Add `copy-to-clipboard` behavior

---

application/forms/Security/RoleForm.php

RoleForm: Force a suffix for all element names

---

doc/02-Installation.md

Fix installation doc for centOS

---

public/js/icinga/loader.js

Cherry 🍒 picked from another not yet merged PR.

Allow to override the actual form action using `formaction` attr

---

library/Icinga/Application/Logger.php
library/Icinga/Exception/IcingaException.php

..everywhere else...
fixes #5079

Check if `\Throwable` instead of `\Exception`..

---

library/Icinga/Web/Response.php
public/js/icinga/loader.js

The server applies the redirection magic now, but only for compatibility reasons.
resolves #4881
closes #4880

js: Always load redirects to their designated target

---

library/Icinga/Common/PdfExport.php

fixes #5083, https://github.com/Icinga/icingaweb2-module-businessprocess/issues/407

PdfExport: Fix empty content in exported pdf

---

library/Icinga/Web/Controller/ActionController.php

ActionController: Always read icingaweb config for csp

---

doc/03-Configuration.md

Fix CSP link in configuration documentation

---

application/controllers/IndexController.php
doc/20-Advanced-Topics.md

Not sure this was wontfix for a reason other than no interest.
Renamed the branch in line with contributing guidelines.
Resolves #766

allow configuring the landing page

---

public/js/icinga/loader.js
public/js/icinga/ui.js

Fix:Remove detail url when no item selected

---

modules/setup/library/Setup/WebWizard.php

WebWizard: Define `icingaweb_schema` as database table

---

modules/setup/application/forms/AdminAccountPage.php

AdminAccountPage: Fix LDAP setup error

---

library/Icinga/Util/Csp.php
public/js/icinga/behavior/collapsible.js

Add missing script-src policy

---

modules/monitoring/library/Monitoring/Object/Macro.php
phpstan-baseline-7x.neon
phpstan-baseline-8x.neon
phpstan-baseline-standard.neon

fixes https://github.com/Icinga/icingaweb2/issues/5168

Fix broken UI when trying to resolve an undefined `$macro$`

---

public/js/icinga/behavior/actiontable.js
public/js/icinga/ui.js

Instead of doing this by default. There are too many cases where this isn't necessary at all.
fixes #5178

js: Explicitly update history when col2 is closed

---

application/views/scripts/navigation/dashboard.phtml

navigation/dashboard: Provide fallback for icingadb items without icon

---

modules/monitoring/application/forms/Command/Object/DeleteDowntimesCommandForm.php

DeleteDowntimesCommandForm: Ignore 404's

---

doc/02-Installation.md

* CC https://github.com/Icinga/packages.icinga.com/pull/45
* CC https://github.com/Icinga/packages.icinga.com/pull/16

.deb: let user install icinga-archive-keyring package

---

modules/monitoring/library/Monitoring/Hook/CustomVarRendererHook.php

CustomVarRendererHook: Log an exception's message and location

---

modules/monitoring/library/Monitoring/Web/Widget/CustomVarTable.php

CustomVarTable: Let the user subgroups fully collapse

---

doc/03-Configuration.md

Adds a small hint about comments in .ini files.

Add hint for comments in ini files

---

library/Icinga/Web/View.php

fix(icons): Service States are not aligned, fix #5290

---

library/Icinga/Authentication/RolesConfig.php

fixes https://github.com/Icinga/icingaweb2/issues/5300

RolesConfig: Add missing column `name` for quick search

---

library/Icinga/Authentication/User/DbUserBackend.php
library/Icinga/Authentication/UserGroup/DbUserGroupBackend.php

Fix case sensitive authentication with postgres

---

modules/monitoring/configuration.php

The same that the reporting module is using now

monitoring: Use the (new) icon for the reporting section

---

library/Icinga/Authentication/User/DbUserBackend.php

DbUserBackend: Fix broken password hash fetch routine

---

library/Icinga/Web/Widget/Dashboard/Dashlet.php
public/js/icinga/events.js

Dashlet: Properly embed iframe urls

---

modules/setup/application/clicommands/ConfigCommand.php
modules/setup/library/Setup/Webserver.php
modules/setup/library/Setup/Webserver/Apache.php
modules/setup/library/Setup/Webserver/Nginx.php

Fix: split fpm-uri flag in socket and url flag

---

public/css/icinga/layout.less
public/css/icinga/menu.less

Fix: spacing and text-breaking

---

library/Icinga/Application/webrouter.php

Fix: PHP built-in server detection for PHP 8.3 SERVER_SOFTWARE format

---

doc/05-Authentication.md

See first sentence of https://icinga.com/docs/icinga-web/latest/doc/05-Authentication/#apache-configuration

Doc: fix over-escaping
