- library/Icinga/Authentication/UserGroup/LdapUserGroupBackend.php
This uses only the username in the memberUid check if the group class is set to posixGroup
> Fix for support issue 9950, do lookups properly on posixGroups

- library/Icinga/File/Ini/IniParser.php
> Use parse_ini_string() where IniParser::parseIni() is not needed

- modules/monitoring/application/views/scripts/list/components/servicesummary.phtml
Correct the count of handled critical services in the hover text in the
status bar.
fixes #2656
> Correct hover text of the status bar

- doc/01-About.md
- doc/02-Installation.md
- doc/03-Configuration.md
- doc/04-Resources.md
- doc/05-Authentication.md
- doc/06-Security.md
- doc/07-Preferences.md
- doc/90-SELinux.md
- doc/99-Vagrant.md
* Move HTML links (<a>...</a>) to the end of the header lines
* This is necessary to allow mkdocs to parse headers correctly and display them in the TOC
* Following sed command was used: sed -i .bu 's/\(<a.*a>\) \(.*\)/\2 \1/g' $filename
> Update docs for better compatibility with mkdocs

- modules/monitoring/library/Monitoring/Command/Renderer/IcingaApiCommandRenderer.php
Icinga 2 v2.7.0 is more strict with the `expiry` attribute if sent
(cannot be null, or in the past).
While acknowledgments with expire time worked well (and do so with this patch),
the command renderer did not check whether the value is actually not null
before setting it into the data form. The boolean value from the checkbox is
not available in the command renderer unfortunately.
@lippserd: Verified working with and without expire time inside the Vagrant boxes.
fixes #2911
> API Commands: Only send acknowledgement expire time if not null

- library/Icinga/Application/Config.php
Since the module copied the array to a local variable, the loaded
Config object never got saved to `static::$modules`
I noticed that during Unit testing, I wasn't able to play with module config in memory. Always had to save to disk...
> Config: Fix cached loading of module config

- library/Icinga/Web/Form/Element/Number.php
This failed me when trying to save the ResourceForm without having set a port number.
is not a valid number
I guess because `$value !== ''` we should also test for null...
> Form/Element/Number: The field should be valid when empty

- .travis.yml
All other builds can happen on trusty.
fixes #2948
> travis: Update build matrix to build with php 5.3 on precise

- application/forms/Config/Resource/DbResourceForm.php
- library/Icinga/Application/Platform.php
- library/Icinga/Data/Db/DbConnection.php
This enables the access to an IBM DB2 database with the driver pdo_ibm.
> Allow pdo_ibm for database resources

- .puppet/manifests/parallels-upgrade-guest-tools.sh
- Vagrantfile
> Vagrant: provision even if upgrading Parallels guest tools isn't possible right now

- Vagrantfile
This PR introduces the following changes to our Vagrantfile:
* All providers use the box `boxcutter/centos7` which supports all our used providers and is not tied to a minor path like the bento boxes
* Devs may customize the Vagratfile locally via .Vagrantfile.local
> Vagrantfile: One box for all providers plus local customization

- modules/monitoring/application/controllers/CommentController.php
- modules/monitoring/configuration.php
Added comment types 'comment' and 'ack' as separate fields and removed
the array syntax due to problems with the filter editor.
fixes #2925
> Remove array syntax from default comment filter

- .travis.yml
- library/Icinga/Authentication/UserGroup/LdapUserGroupBackend.php
- library/Icinga/Protocol/Ldap/LdapUtils.php
- library/Icinga/Repository/LdapRepository.php
- test/php/library/Icinga/Protocol/Ldap/LdapUtilsTest.php
- test/travis-ldap.ini
This PR addresses issues in resolving DN and memberships under Active Directory, and other LDAP that use DN for membership information.
Icingaweb2 tries to detect if the membership attribute of groups is a DN.
The decision was based on comparing a found sample value to the configured base DN.
Let's say we have a LDAP base: `dc=germany,dc=example,dc=com`
We try to detect memberships, and by lucky chance retrieve a value like this:
cn=techaccount123,ou=groups,dc=example,dc=com
This is of course a entity of another domain, but referenced here.
Icingaweb2 compares that value, by expecting that `dc=germany,dc=example,dc=com` would be part of its domain. Which of course is not.
The assertion fails, and icingaweb2 does not resolv memberDN to username. The user can't be assigned to any group. …
> Problems in LDAP membership resolution

- modules/monitoring/application/forms/Command/Object/ScheduleHostDowntimeCommandForm.php
Adds support for an optional option 'hostdowntime_all_services' in the settings section of the monitoring options. If set to true, this will make the "All Services" checkbox in the schedule host downtime form default to checked.
> Option for default schedule downtime for all services

- modules/translation/doc/03-Translation.md
Changed module name from ``module`` to ``yourmodule`` according to the example description.
> Doc: Fix module name in translation example

- public/js/icinga/events.js
- public/js/icinga/loader.js
Icinga offers the user to enable or disable 'auto-refresh' with a
static preference.
But 'auto-refresh' is the default and our users often have dozens of
Icinga tabs open in their browser, which they are not looking at.
The background tabs lead to significant load on the database from
repetitive queries to keep the invisible UI fresh.
This PR adds a visibility listener, which disables auto-refresh when the
page is not visible.
Fixes #2761
> Disable auto-refresh when page is not visible

- doc/02-Installation.md
Install `icingacli` (as for other distros) to avoid `The program 'icingacli' is currently not installed. You can install...`
> Update installation step for Ubuntu

- modules/monitoring/application/clicommands/ListCommand.php
The help text still showed the wrong paramter, while it was not documented
as possible parameter either. In addition to that #562 unveils that a
custom --format parameter requires selected columns to do so.
This patch adds that into the documentation which is rendered as CLI command
help text then.
refs #562
> Fix help for icingacli monitoring list (--unhandled is --problems, etc.)

- library/Icinga/Authentication/User/DbUserBackend.php
The existing usage of crypt() was borderline incorrect. This simplified function will allow hashes of other types (e.g. bcrypt) and thus mitigate #2954 (use password_hash) until this can be implemented.
The getSalt protected method was also removed as this is no longer required, though this can be added again in future.
I will make an additional pull request to migrate to bcrypt with crypt.
> Modify authentication function to support alternative algorithms

- modules/translation/library/Translation/Util/GettextTranslationHelper.php
Some of our modules ship vendor data, or tend to add scripts adding icingaweb2 and other modules with a vendor/ directory.
This patch avoids the translation tool to scan these directories for translation calls.
> GetTextTranslationHelper: Make sure we ignore any dotfile or vendor dir

- modules/monitoring/library/Monitoring/Controller.php
When calling /icingaweb2/monitoring/health/info?format=json you get a php error because we ask for query on query object.
<b>Fatal error</b>:  Uncaught Error: Call to undefined method Icinga\Module\Monitoring\Backend\Ido\Query\ProgramstatusQuery::getQuery() in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Controller.php:49
This PR fixes this
> Fix php fatal error on monitoring/health/info when asking for json

- library/Icinga/Authentication/AdmissionLoader.php
If the users directive contains at least one single asterisk, the role is applied to all users.
So, this supports roles which define users=username, ..., * and users=*
Fixes #3095
> Apply role to all users if the role is defined with users=*

- modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
Custom variables added via the URL parameters addColumns or sort must be added to the GROUP BY list when using PostgreSQL.
Fixes #1873
> pogsql: Group by custom variables when querying them

- library/Icinga/Application/Web.php
Web::setupFrontController() took the user object into account when checking for disabled stacktraces.
But we changed our bootstrap order some time ago so we did not have a user in this method anymore.
Now, Web::setupUser() checks for disabled stacktaces in the user prefs instead.
Fixes #2595
> Fix that disabled stack straces via user prefs had no effect

- doc/02-Installation.md
This was added to help users getting started since:
* We no longer install httpd as requirement
* Fedora 27 needs manual work choosing php-fpm or mod_php
> doc: Add installation notes for web server

- doc/20-Advanced-Topics.md
The command 'icingacli setup config directory' actually produces the
configuration files for Icinga Web 2 instead of the command 'icingacli
setup config webserver'.
> doc: Use correct command for configuration generation

- doc/02-Installation.md
- modules/setup/library/Setup/Webserver/Apache.php
- packages/files/apache/icingaweb2.fpm.conf
Apache < 2.4 does not support `SetHandler` in a `FilesMatch` block. The PR introduces `IfVersion` blocks to support FPM for both Apache >= 2.4 and Apache < 2.4.
> FPM Config: Support Apache < 2.4

- modules/doc/library/Doc/DocParser.php
> Don't interpret shell comments inside fenced code blocks as MD headers

- modules/setup/library/Setup/Webserver/Apache.php
- packages/files/apache/icingaweb2.conf
- packages/files/apache/icingaweb2.fpm.conf
For authenticating against the Icinga Web 2 API.
Suggested in https://github.com/Icinga/icinga-packaging/issues/71
FYI @SimonHoenscheid
fixes #3173
> Support basic auth on PHP-FPM

- modules/monitoring/library/Monitoring/Backend/Ido/Query/EventhistoryQuery.php
- modules/monitoring/library/Monitoring/DataView/Eventhistory.php
Not used anywhere and not working for a long time already,
at least as filter columns.
If someone wants to see aggregated summaries over different event types there's still the timeline.
fixes #2860
> EventHistory: Drop obsolete SUM aggregates

- modules/setup/application/clicommands/ConfigCommand.php
- modules/setup/library/Setup/Webserver.php
- modules/setup/library/Setup/Webserver/Apache.php
- modules/setup/library/Setup/Webserver/Nginx.php
Allows to pass a different socket path than the default
when generating a webserver's configuration.
fixes #2862
> Add fpm socket commandline switch when generating a webserver's configuration

- public/js/icinga/behavior/actiontable.js
This event is triggered due to delegation. If any onclick event is able to bubble up this far that it gets triggered we can safely use whatever it has been triggered for. (i.e. it can only be a tr[href])
fixes #3298
> actiontable.js: Use `event.currentTarget` instead of the closest tr

- library/Icinga/Exception/IcingaException.php
> IcingaException::getConfidentialTraceAsString(): don't fail on internal functions

- .puppet/files/etc/profile.d/env.sh
- .puppet/profiles/icingaweb2_dev/manifests/init.pp
This avoids having to set `PATH="/opt/rh/rh-php71/root/bin:$PATH" icingacli`
all the time.
> Vagrant: Install SCL PHP CLI and set PATH

- .puppet/manifests/site.pp
- .puppet/profiles/base/manifests/init.pp
This happened too often with `vim: not found`, so I've patched it.
> Vagrant: Introduce base profile and install vim

- application/controllers/AuthenticationController.php
- application/forms/Authentication/LoginForm.php
- library/Icinga/Application/Hook/AuthenticationHook.php
With this patch, we have created a new Hook that allows modules to authenticate the user in third-party applications during login and logout actions.
The implementation of the onLogin and onLogout methods of the hook are not mandatory.
A use case is to authenticate the user in grafana trough the login of icingaweb.
This is an example of how we have implemented the AuthenticationHook for Grafana.
```php
<?php
namespace Icinga\Module\Analytics\ProvidedHook;
use Icinga\Application\Hook\AuthenticationHook;
use Icinga\Application\Logger;
use Icinga\User;
class Authentication extends AuthenticationHook
{
const GRAFANA_SESS = "grafana_sess";
public function onLogin(User $user)
{
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "http://localhost:3000/login");
curl_setopt($ch, CURLOPT_HTTPHEADER, …
```
> Authentication Hook

- public/css/icinga/menu.less
> menu: Only invert icons located under /img/icons/

- library/Icinga/Application/Platform.php
PDO Implementation of zf1 builds on module mssql OR pdo_dblib, while dblib is preferred.
Newer implementations would support pdo_sqlsrv, but that is not available with ZF1.
> Platform: Correct detecting MSSQL Support

- library/Icinga/Application/Platform.php
- library/Icinga/Data/Db/DbConnection.php
Utilizes the `sqlsrv` extension automatically if it's available and none is explicitly configured.
fixes #3320
> Add support for the sqlsrv extension

- modules/monitoring/application/views/helpers/PluginOutput.php
- modules/monitoring/test/php/application/views/helpers/PluginOutputTest.php
Trailing text was lost in processing.
Also add tests to check this behavior plus some basics.
fixes #3382
> PluginOutput: Fix text splicing for status tags in HTML output

- library/Icinga/Data/Db/DbConnection.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
Utilizes the `charset` configuration value to dynamically generate a `COLLATE` instruction. Still falls back to `latin1` if not set.
fixes #2508
> Fix search over customvars results in sql error 2508

- modules/monitoring/application/views/scripts/list/notifications.phtml
In history list we need to see always the full date + time when a notification was send and not only "on Mar 9" or similar and have to do mouseover to see the time.
View as it is now:
New view:
> Always show full date + time on history list for notifications

- library/Icinga/Web/Session.php
- library/Icinga/Web/Session/Php72Session.php
- library/Icinga/Web/Session/PhpSession.php
- test/php/library/Icinga/Web/Session/PhpSessionTest.php
> Don't call session_start() after ini_set()

- test/php/library/Icinga/File/Storage/LocalFileStorageTest.php
... not to cause side effects in other tests
> LocalFileStorageTest: restore error_reporting() level and error handler

- library/Icinga/Application/Logger.php
- library/Icinga/Util/Json.php
- library/Icinga/Web/Announcement/AnnouncementCookie.php
- library/Icinga/Web/Response/JsonResponse.php
- modules/monitoring/application/clicommands/ListCommand.php
- modules/monitoring/library/Monitoring/Controller.php
- modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php
- modules/monitoring/library/Monitoring/Web/Rest/RestRequest.php
> Json::encode(): auto-sanitize bad UTF-8 strings

- library/Icinga/Application/Web.php
We initialize modules before we set up the user backend and other
singletons. But modules may access those in order to check the
permissions of the authenticated user for example. With this fix,
modules are loaded once all other bootstrap tasks have been completed.
fixes #3470
> Bootstrap modules at last

- doc/02-Installation.md
The documentation was missing and it just said: 
> Debian / Ubuntu
> Your web server should be up and running after the installation.
Fixed this and added a short how-to test it.
> Documentation for the webserver installation on Debian

- library/Icinga/Web/Controller/ActionController.php
- public/js/icinga/loader.js
We've got three methods for redirection in our ActionController:
* `redirectNow`
* `redirectHttp`
* `redirectXhr`
Though, they behave in no way differently in which method to use for the actual redirection.
That's why I'm proposing to introduce a new header and transmitting it by default when using `redirectHttp`.
This way, utilizing this method actually causes our JS to issue a true HTTP redirect.
@lippserd Would be cool if we'd get this into 2.6, if it's reasonable to implement it this way.
> Let redirectHttp use HTTP for redirection

- application/layouts/scripts/body.phtml
- application/views/scripts/mixedPagination.phtml
- library/Icinga/Web/Widget/Tab.php
- library/Icinga/Web/Widget/Tabs.php
Only a real issue with <= IE9 as other browsers properly escape
urls prior transmission.
> Fix some XSS vulnerabilities

- public/js/icinga/loader.js
Adds another call to the event loop regarding focus/scroll stuff. We have not enough competing calls of this type yet.
Eh, on a more serious note: I can't/won't provide a more sophisticated solution since fixing this properly in this crappy code results only in a headache and wasted time.
fixes #3492 
@lippserd I don't mind if you won't approve this. But please demand a proper fix from yourself or someone else then. (`public/js` -> :fire: )
> loader.js: Make anchor navigation working again

- modules/monitoring/library/Monitoring/Command/Transport/ApiCommandTransport.php
$data may be arbitrarily nested.
fixes #3535
> Audit: Log a command's payload as json

- application/controllers/AuthenticationController.php
- application/layouts/scripts/external-logout.phtml
- application/views/scripts/authentication/logout.phtml
We've used the standard layout before which caused a automatic login.
Automatic because the browser saw our js/css <link> tags and accessed
the routes which in turn logged in the user, but only if there's a
enabled module which's configuration.php (or run.php) accesses the
Auth singleton. The stripped down layout provides its own js/css so
there's no need for our full-blown resources.
fixes #3583
> auth/external: Use a stripped down layout for the logout workaround

- library/Icinga/Application/Modules/Module.php
- library/Icinga/File/Ini/IniParser.php
As reported by Max in [Debian Bug #914457 - icingacli: any command issued to icingacli rise an exception](https://bugs.debian.org/914457):
> an example:
> ```
> icingacli --help
>
> Fatal error: Uncaught ErrorException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/php/Icinga/File/Ini/IniParser.php:67
> Stack trace:
> #0 /usr/share/php/Icinga/Application/ClassLoader.php(303): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, '"continue" targ...', '/usr/share/php/...', 67, Array)
> #1 /usr/share/php/Icinga/Application/ClassLoader.php(303): require()
> #2 [internal function]: Icinga\Application\ClassLoader->loadClass('Icinga\\File\\Ini...')
> #3 /usr/share/php/Icinga/Application/Config.php(326): …
```
> Use continue <N> in case statements to fix ErrorException with PHP 7.3.

- application/forms/Config/Resource/DbResourceForm.php
- library/Icinga/Data/Db/DbConnection.php
When only a database name is specified, Oracle can use alternative methods to find the database.
ref/NC/588829
> DbConnection: Make host optional for Oracle connections

- application/forms/Config/Resource/DbResourceForm.php
Mainly used for Oracle
refs #3643
ref/NC/589845
> DbResourceForm: Remove default value for host when not required

- library/Icinga/Authentication/Auth.php
If a specific User-Backend has been assigned to a Group Backend, and
the User has been authenticated by another User-Backend, then there is
no need to ask the unrelated Groups Backend for membership.
> Auth: do not ask for unrelated group membership

- modules/monitoring/application/views/helpers/PluginOutput.php
- modules/monitoring/test/php/application/views/helpers/PluginOutputTest.php
> Don't escape html entities in plugin output twice

- modules/monitoring/application/views/scripts/tactical/index.phtml
The legend badges used the same classes as the donuts - so the background colour could be set via ```@state-xxx``` but the font colour could not be overwritten unless the non-standard class ```.slice-state-xxx``` was overwritten.
Now it should have the normal theming behaviour.
> Fix tactical overview legend badges not properly affected by themes

- public/js/icinga/loader.js
- public/js/icinga/ui.js
- public/js/icinga/utils.js
Restores the scroll position if:
* it's been a POST request
* the source and target url path is the same
* the target's url params do not change significantly
> Preserve scroll position upon form submits

- library/Icinga/File/Ini/IniParser.php
- test/php/library/Icinga/File/Ini/IniParserTest.php
> Fix php ini parser does not strip trailing whitespace

- application/layouts/scripts/layout.phtml
- public/js/icinga/loader.js
- public/js/icinga/ui.js
- public/js/icinga/utils.js
As the proposed solution in #3609.
Alternatively we may also introduce a new header `X-Icinga-ContainerId` to ensure compatibility with code directly working with `Icinga\Web\Request::protectId()`. Our view helper and form may then apply the containerId when protecting ids.
fixes #3609 
fixes #2238
> Fix window id cannot be used to differentiate containers

- doc/05-Authentication.md
Hi, 
I fixed some incorrections in the doc/05-Authentication.md. The information for group_member_attribute was incorrect. 
I double checked the default values, should be fine now.
Cheers,
Markus
> Fix documentation for LDAP Groups

- library/Icinga/Protocol/Ldap/LdapQuery.php
LDAP peforms case-insensitive checks by default so do we now.
fixes #3650
> Fix LDAP group members not found

- library/Icinga/Cli/Command.php
Can not do this in cli context:
$this->Config('redis')
ERROR: ErrorException in /vagrant/icingaweb2/library/Icinga/Cli/Command.php:81 with message: array_key_exists() expects parameter 2 to be array, null given
> Fix uninitialized array and module in Cli\Command

- modules/monitoring/application/controllers/HostsController.php
- modules/monitoring/application/controllers/ServicesController.php
- modules/monitoring/application/views/scripts/hosts/show.phtml
- modules/monitoring/application/views/scripts/services/show.phtml
- modules/monitoring/library/Monitoring/Hook/DetailviewExtensionHook.php
- modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php
Also make sure Javascript module handling will find the container for module auto-loading.
@lippserd Please review if this makes sense.
fixes #3072
> Integrate DetailviewExtension into multi-select views

- public/css/icinga/layout-structure.less
Fix for ul.tabs links not being visible in showFullscreen mode (white links on white background)
> Set background color on Fullscreen Layout ul.tabs

- modules/setup/application/clicommands/ConfigCommand.php
- modules/setup/library/Setup/Webserver.php
- modules/setup/library/Setup/Webserver/Apache.php
- modules/setup/library/Setup/Webserver/Nginx.php
The FPM block is commented out every time, even when called with the option `--fpm-uri` introduced in 2a959af9c2054a014f0ea6e059df70e495f3d4a8
```
$ ./bin/icingacli setup config webserver apache --document-root /usr/local/icinga/icingaweb2/public --config /usr/local/icinga/icingaweb2/etc --fpm-uri 127.0.0.1:9000
Alias /icingaweb2 "/usr/local/icinga/icingaweb2/public"
#<IfVersion < 2.4>
#</IfVersion>
<Directory "/usr/local/icinga/icingaweb2/public">
Options SymLinksIfOwnerMatch
AllowOverride None
DirectoryIndex index.php
<IfModule mod_authz_core.c>
<RequireAll>
Require all granted
</RequireAll>
</IfModule>
<IfModule !mod_authz_core.c>
Order allow,deny
Allow from all
</IfModule>
SetEnv ICINGAWEB_CONFIGDIR "/usr/local/icinga/icingaweb2/etc"
EnableSendfile Off
<IfModule mod_rewrite.c> …
```
> Setup: Allow to enable FPM

- doc/02-Installation.md
Instruct users to retrieve APT keys via a secure connection to avoid
man-in-the-middle attacks.
> Update documentation to fetch keys securely

- library/Icinga/Application/Cli.php
- library/Icinga/Cli/Command.php
`Icingacli` should return non-zeno status code when display usage messages
for example with invalid commands
https://github.com/Icinga/icinga2/issues/6585
It is good for automation and helps mitigate typing errors
> Return non-zero on display usage

- modules/test/application/clicommands/PhpCommand.php
Some modules may require their very own phpunit configuration in order to run.
> tests: Don't include non-enabled modules

- public/js/icinga/loader.js
Got changed with f12a5741b8a4c53b7e5d94e43094e18d5a946934. Triggering
rendered events for stuff that's never displayed doesn't seem right.
> loader.js: Return in onComplete upon handled redirects

- modules/monitoring/application/controllers/ListController.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/EventgridhostsQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/EventgridservicesQuery.php
- modules/monitoring/library/Monitoring/DataView/Eventgridhosts.php
- modules/monitoring/library/Monitoring/DataView/Eventgridservices.php
I would like to submit for consideration this pull request to improve "event grid" performance in the monitoring web 2 module.
This patch partially addresses the issue 12732 - Improve IDO query performance.
The patch works by limiting the backend query for events by date, and also selecting only hosts or services in the main subquery (according to what is requested in the form).
In some rough testing on a large system with many (too many...) events, these changes reduced the initial page load time of the Event Grid from over 5 minutes to under 20 seconds.
> Improve Event Grid performance

- public/js/icinga/behavior/navigation.js
- public/js/icinga/events.js
> Make ctrl-click open new tab

- modules/monitoring/application/views/scripts/health/info.phtml
We have infrastructure like this:
And when I'm gonna to explore IcingaWeb logs it becomes a real pain to find proper node.
So I added info about icingaweb endpoint when using IcingaWeb in HA mode and it works for us.
In UI it looks like this:
I hope it is usefull. 
Please let me know if you think it should be another page to display that info.
Thanks,
Ivan
> Added info about icingaweb endpoint into "System -> Monitoring Health" section

- modules/monitoring/library/Monitoring/Backend/Ido/Query/HostnotificationQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicenotificationQuery.php
I'd like to submit this pull request for consideration to address a problem (Issue 2266) where attempts to filter the "Output" field in the "Event Overview" cause an error to be dumped to the interface (SQLSTATE[HY000]: General error: 1111 Invalid use of group function, query was:....)
Implements a special handling of notification 'output' field to avoid using aggregate function in WHERE clause of query.
fixes #2266
> Fixes 2266.  Special handling of notification 'output' field.

- library/Icinga/Web/StyleSheet.php
CLI commands which require our LESS parser had no access to our CSS
because the public path was set to the path of the icingacli executable
which is most likely bin.
> CLI: Fix CSS path

- library/Icinga/Data/SimpleQuery.php
Our monitoring list views call SimpleQuery::hasResult() first in
order to determine whether there are results to display. This calls
fetchRow() which executes the underlying query the first time. If there
are resulsts, the query is iterated which executes the query again.
With this patch, SimpleQuery::hasResult() makes use of the inner
iterator instead of calling fetchRow(). The query is now executed only
once.
<h1>Without patch</h1>
<table class="benchmark">
<tbody><tr><td align="left">Description</td><td align="right">Off (ms)</td><td align="right">Dur (ms)</td><td align="right">Mem (diff)</td><td align="right">Mem (total)</td></tr>
<tr><td align="left">Bootstrap, autoloader registered</td><td align="right">0.003</td><td align="right">0.003</td><td align="right">682.06 KiB</td><td …
> Fix double query execution

- library/Icinga/Web/FileCache.php
- library/Icinga/Web/Helper/HtmlPurifier.php
- library/Icinga/Web/Helper/Markdown.php
- library/Icinga/Web/View/helpers/string.php
- library/Icinga/Web/Widget/Announcements.php
- library/Icinga/Web/Widget/ApplicationStateMessages.php
- modules/monitoring/application/controllers/EventController.php
- modules/monitoring/application/views/scripts/downtime/show.phtml
- modules/monitoring/application/views/scripts/partials/comment/comment-detail.phtml
- modules/monitoring/application/views/scripts/partials/downtime/downtime-header.phtml
- modules/monitoring/application/views/scripts/partials/event-history.phtml
- modules/monitoring/application/views/scripts/show/components/acknowledgement.phtml
- modules/monitoring/application/views/scripts/show/components/comments.phtml
- modules/monitoring/application/views/scripts/show/components/downtime.phtml
- modules/monitoring/application/views/scripts/show/components/notes.phtml
Adds a new view helper `Markdown` which allows to transform markdown.
`$this->markdown($text)`
At the moment markdown is transformed for notes, comments and announcements. (yep, I thought this suits here as well)
resolves #3684 
resolves #3441 
resolves #2831
> Make notes, comments and announcements markdown aware

- modules/monitoring/application/views/scripts/tactical/index.phtml
- modules/monitoring/configuration.php
- public/css/icinga/widgets.less
> Add tactical overview to global search

- application/controllers/DashboardController.php
- application/forms/Dashboard/DashletForm.php
- application/views/scripts/dashboard/settings.phtml
- doc/80-Upgrading.md
- library/Icinga/Application/Modules/Module.php
- library/Icinga/Legacy/DashboardConfig.php
- library/Icinga/Web/Navigation/DashboardPane.php
- library/Icinga/Web/Widget/Dashboard.php
- library/Icinga/Web/Widget/Dashboard/Dashlet.php
- library/Icinga/Web/Widget/Dashboard/Pane.php
- modules/migrate/application/clicommands/DashboardCommand.php
Introduces a major breaking change. All non-english users need to adjust their dashboard.ini after this change. (In case they've adjusted dashlets provided by modules)
Missing:
fixes #3542
> Don't translate pane and dashlet names in configs

- modules/monitoring/application/views/scripts/partials/event-history.phtml
- modules/monitoring/library/Monitoring/Backend/Ido/Query/EventhistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/HostnotificationQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/NotificationhistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicenotificationQuery.php
- modules/monitoring/public/css/tables.less
fixes #2963 
@nilmerg This depends on the Markdown `<p>` in `<p>` rendering fix and should be reviewed once we have this.
> Fix confusing downtime notification history

- modules/monitoring/application/views/helpers/Customvar.php
- modules/monitoring/application/views/helpers/Perfdata.php
- modules/monitoring/application/views/scripts/partials/object/detail-content.phtml
- modules/monitoring/application/views/scripts/show/components/notes.phtml
- modules/monitoring/application/views/scripts/show/components/output.phtml
- modules/monitoring/application/views/scripts/show/components/perfdata.phtml
- public/css/icinga/main.less
- public/js/icinga/behavior/collapsible.js
- public/js/icinga/storage.js
The following details now collapse:
* Plugin output
* Plugin perfdata
* Custom variables
* Notes
Plugin output and perfdata are grouped by their check_command name. For example, expanding `disk`'s output on host `localhost` expands it for every other host which has this check.
All custom variables are grouped by their object's type. Once custom variables are expanded for a service every other service has its variables also expanded. The same applies for notes.
resolves #3566
> Collapsible plugin output

- public/js/icinga/behavior/navigation.js
- public/js/icinga/storage.js
The sidebar state is now maintained per tab/window because users view
different things in different tabs/windows. E.g. users work with a
specific module constantly clicking through the menu while having
other tabs/windows with some important dashboards open.
When the sidebar is closed in one tab/widnow, it should not close
the sidebar in the other tabs/windows.
> Maintain sidebar state per tab/window

- public/css/icinga/compat.less
Some 3rd party modules (e.g. vsphere) use this mixin (though we never had it).
With lessphp version 0.5.0 using undefined mixins now throws exceptions.
Since we can't rely that users upgrade those modules first,
we provide the mixin for compatibility here.
> Compat: Provide empty LESS mixin .code()

- library/Icinga/Data/Filter/FilterChain.php
- modules/monitoring/application/controllers/TacticalController.php
- modules/monitoring/application/views/scripts/list/hostgroups.phtml
- modules/monitoring/application/views/scripts/list/servicegroups.phtml
- modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php
Before, combined membership filters were only possible in filter expressions, e.g. `hostgroup_name=(a&b)`.
Now, also `(hostgroup_name=a&hostgroup_name=b)` is supported (even w/o the parantheses) which makes it easier to build such filters with the filter editor.
> Support subquery filters in filter chains

- modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php
With this commit the version prefix character is treated as optional
which always used to be 'r' or 'v'. But this is gone since Icinga 2
version 2.11.0 RC1.
> Fix Icinga 2 version detection

- modules/monitoring/library/Monitoring/Backend/Ido/Query/EventgridQuery.php
PostgreSQL fails with failed to find conversion function from
unknown to text. PostgreSQL won't detect the type of object_type.
Most likely because it's used in a CASE statement and provided by a
subquery:
select case when s.object_type = 'service' then 1 else 0 end from
(select ('service') as object_type) as s;
This commit just removes object_type from the CASE statements because we
don't need them anyway. Recently we've changed the event grid query to
only select hosts or services and not both.
> Fix Event Grid PostgreSQL error

- library/Icinga/Data/SimpleQuery.php
The reverted commit fixed a double query execution bug by only executing
the query once in either SimpleQuery::hasResult() or upon iteration.
But the fix  introduced two problems:
* Default sort rules no longer work
* Show more links missing
We work with DataView objects in our controllers and views. When
iterating over a DataView, it applies its default sort rules and then
returns the underlying query, see DataView::getIterator().
DataView::hasResult() on the other hand does not apply the default sort
rules. So, if hasResult() is called first, the default sort rules are no
longer applied because the query will be executed only once.
The fix would be as easy as to apply sorting in DataView::hasResult() as
well.
But now the show more part kicks in. We know whether there are more
results …
> Revert "Fix double query execution"

- public/css/icinga/forms.less
We now also use the ::placeholder pseudo-element selector instead of
several vendor prefixes.
fixes #3847
> Forms: Distinguish placeholders from real values

- modules/monitoring/public/css/module.less
Doesn't apply to all markdown content. Our only use-case is in the monitoring module and this already got known style for external/custom links.
Other modules may want to apply a different style or possibly none at all.
resolves #3888
> Highlight links in monitoring's markdown content

- library/Icinga/Application/Modules/DashboardContainer.php
- library/Icinga/Application/Modules/Module.php
- modules/monitoring/configuration.php
Allows modules to define a priority for dashlets. Just as it is possible for menu entries.
@lippserd I opted for this because I suspect we need such a priority anyway for #3809.
fixes #3931
> Fix wrong dashlet order

- library/Icinga/Web/Widget/FilterEditor.php
Simple values are wrapped with `*` anyway, so trimming all
whitespace doesn't pose an issue. (Even if inserted intentionally)
This doesn't apply to qualified search values. (e.g. `host = abc `)
resolves #4002
> Also trim trailing whitespace from search values

- public/css/icinga/base.less
- public/css/icinga/forms.less
Move colours to base less, so people who build themes have a better overview over which colours can and should be changed.
Especially since those colours are not form-exclusive anymore in Icinga DB.
> Move form colours to the base.less

- modules/monitoring/application/forms/Config/SecurityConfigForm.php
- modules/monitoring/library/Monitoring/Object/MonitoredObject.php
This PR introduces a new configuration option and filter for hiding specific customvars in the detail view of a host or service. It uses the same matching syntax as the existing blacklist feature.
Should be useful in environments which make heavy use of apply rules on customvars, which are often cryptic and bloat the customvar section in web.
> Introduce option to hide specific customvars in web

- library/Icinga/Data/Db/DbConnection.php
MySQL 8+ seems a bit more strict now.
fixes #3740
> Set `COLLATE 'latin1_general_ci'` for `latin1` charsets on MySQL connections

- application/layouts/scripts/body.phtml
- application/layouts/scripts/parts/navigation.phtml
- modules/monitoring/application/views/scripts/list/hosts.phtml
- modules/monitoring/application/views/scripts/list/services.phtml
- modules/monitoring/public/css/module.less
- public/css/icinga/layout-structure.less
- public/css/icinga/layout.less
- public/css/icinga/menu.less
- public/css/icinga/responsive.less
- public/css/icinga/setup.less
- public/css/icinga/tabs.less
- public/css/themes/Winter.less
- public/css/themes/solarized-dark.less
- public/js/icinga/behavior/application-state.js
- public/js/icinga/behavior/filtereditor.js
- public/js/icinga/behavior/navigation.js
- public/js/icinga/events.js
- public/js/icinga/loader.js
- public/js/icinga/ui.js
Flexbox layout is now implemented.
resolves #3810 
Some notes:
* It works fine in recent versions of Chrome, Safari and Firefox (I tested on macOS, we should test other OSes)
* It works surprisingly great in Edge
* It works in IE 11. Though there are some minor inconsistencies.
* Layout is completely broken in IE 10 and below. It might be possible to get it to work, but imho not with a reasonable amount of effort, since IE 10 basically supports flex-box but uses an older version with different syntax and required `-ms`-prefixes
> Rework layout with flexbox

- modules/monitoring/application/views/scripts/object/detail-tabhook.phtml
- modules/monitoring/library/Monitoring/Hook/ObjectDetailsTabHook.php
- modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php
This is an implementation of a new hook that allows to add custom tab to the detail view on monitoring for hosts and services.
> Add custom tab hook

- modules/monitoring/application/controllers/EventController.php
- modules/monitoring/application/views/scripts/event/show.phtml
- modules/monitoring/library/Monitoring/Hook/EventDetailsExtensionHook.php
Add the possibility to insert custom HTML in EventController, right after the Details table. The Hooks must implement a function getHtmlForEvent that should return an HTML string, that will be directly rendered in Show.phtml.
> Add EventDetailsExtensionHook and include it into EventController

- modules/setup/application/locale/de_DE/LC_MESSAGES/setup.po
At the end of the Icinga Web 2 setup procedure, there's a nice welcome greeting.
Since there's no database name in the [original message], there's no text that could be replaced by the %s.
This is untested. Please let me know if there are other lines/files that have to be changed in order to make this work.
Kind regards,
Bernd
[original message] https://github.com/Icinga/icingaweb2/blob/81bb5272b59491ad021bcf0a5fefc582ce0112c4/modules/setup/library/Setup/Steps/DatabaseStep.php#L252
> Fixed %s database name in DE translation

- library/Icinga/Web/Url.php
Before, sublcasses of Url suffered from @return Url hints. This is
@return static now.
> Url: Fix @return hints

- public/js/icinga/history.js
Before, we only had pushCurrentState() to add a new URL to the history
stack. But some actions, e.g. "load more" in history views require to
replace the current state instead of pushing. This is what
replaceCurrentState() supports now.
> JS: Introduce Icinga.History.replaceCurrentState()

- library/Icinga/Web/Controller/ActionController.php
- library/Icinga/Web/Request.php
- library/Icinga/Web/Response.php
- library/Icinga/Web/Window.php
Since #3610 any code working with the window ID also differentiates now between containers. This was to be expected but not identified as an issue. Though, it is an issue with the businessprocess module and the director. :fireworks: 
Now, any code utilizing `Window::getInstance()->getId()` or `Window::getInstance()->getSessionNamespace()` only differentiates between windows again. ID protection is still based on container IDs.
> Fix server side window handling

- public/js/icinga/ui.js
Though IDs should be unique across the whole page, focusElement() must
not fail if there is the same anchor in the left and right column.
focusElement() now also respects the container when searching the
element to focus by ID.
> JS: Respect container in Icinga.Ui.focusElement()

- library/Icinga/Application/Cli.php
- library/Icinga/Authentication/Auth.php
Since version 2.7.x CLI actions load all enabled modules automatically.
This includes launching configuration.php and run.php. Though code
in those files should be restricted to a supported set of functions,
module devs may write any code here. If a module requires authentication
in those files, CLI actions fail because there is no auth possible.
With this patch, we setup a fake user named "cli" w/o any permission when
running CLI actions.
> CLI: Setup fake auth

- application/forms/Control/LimiterControlForm.php
- library/Icinga/Web/Widget/Dashboard/Dashlet.php
- library/Icinga/Web/Widget/SortBox.php
- modules/monitoring/application/controllers/ListController.php
- public/css/icinga/controls.less
- public/css/icinga/forms.less
- public/css/icinga/layout.less
- public/css/icinga/menu.less
> Fix main layout for use without js

- public/js/icinga/loader.js
... not to break the container with the reverse proxy's response not fitting into our layout.
fixes #1092
fixes #4133
> Icinga.Loader#onFailure(): treat 5xx response as connection failure

- modules/monitoring/library/Monitoring/Backend/Ido/Query/HostnotificationQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicenotificationQuery.php
Fixes an Exception when searching for a specific alias (as offered in
the filter form)
> Query\*notificationQuery: add missing host_alias

- doc/04-Resources.md
- library/Icinga/Protocol/Ldap/LdapConnection.php
We automatically detect whether the server supports server side sorting
and sort manually if that is not the case. But there are LDAP servers
which report that they support this feature in general but have it
disabled for certain fields.
If we send the server side control for any field that has server side
sort disabled, the LDAP server will abort the query.
With the new configuration option it is possible to disable server side
sorting and it has precedence over our automatic detection.
Since this is a very special LDAP server configuration, there is no GUI
option for this.
ref/IP/24737
> LDAP: Add option to disable server side sorting

- library/Icinga/Application/Modules/Module.php
Because assets are not registered in the CLI context,
CLI actions cannot access the full style sheet.
This is necessary for Icinga Reporting though in order to send PDF reports.
> CLI: Also register assets

- doc/80-Upgrading.md
- library/Icinga/Web/Controller.php
- library/Icinga/Web/Controller/ActionController.php
- library/Icinga/Web/Url.php
- library/Icinga/Web/Widget/FilterEditor.php
- modules/monitoring/application/controllers/ListController.php
- modules/monitoring/application/controllers/ServicesController.php
- modules/monitoring/application/views/scripts/list/comments.phtml
- modules/monitoring/application/views/scripts/list/contacts.phtml
- modules/monitoring/application/views/scripts/list/downtimes.phtml
- modules/monitoring/application/views/scripts/list/hostgroups.phtml
- modules/monitoring/application/views/scripts/list/hosts.phtml
- modules/monitoring/application/views/scripts/list/notifications.phtml
- modules/monitoring/application/views/scripts/list/servicegroups.phtml
- modules/monitoring/application/views/scripts/list/services.phtml
- modules/monitoring/application/views/scripts/partials/event-history.phtml
- modules/monitoring/application/views/scripts/partials/show-more.phtml
- modules/monitoring/library/Monitoring/DataView/DataView.php
- public/js/icinga/behavior/modal.js
Changes how Icinga Web 2 handles compact layout requests.
Previously:
* Parameter `showCompact[=1]` allows to request compact layout but is available only to controller code accessing `$this->params`
* Parameter `view=compact` allows the same, but is also available to the global `Icinga\Web\Request` object
Changed:
* Parameter `showCompact[=1]` is left unchanged
* Parameter `view=compact` is now also only available to controller code accessing `$this->params`
`view=compact` is now also deprecated. Anyone using this parameter to request compact layouts should switch to `showCompact[=1]`.
> Fix view compact handling

- modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php
latin1 seems to be the only supported charset for MySQL but the current upstream default charset is utf8mb4.
It would be preferable to switch the charset used by icinga to utf8mb4 and the corresponding collations but since there doesn't seem to be any intention of doing this, latin1 should be set explicitly.
This is even more important since the IdoMysqlConnection does not have an attribute to set the charset manually.
This does not seem to be the best place to set the charset but it does not seem that it is used by anything other than the MySQL adapter.
This fixes issues such as #3682 that have been closed prematurely and have nothing to do with the charset of the tables.
> Set default IDO charset to latin1

- library/Icinga/Authentication/User/DbUserBackend.php
The BINARY cast to make trailing spaces significant (#4030) also
made these queries case-sensitive. This wasn't identified at the
time because the query itself wasn't case-insensitive, but the
default collation on the `name` column. (Tests sometimes are the
perfect mitigation for this...)
fixes #4184
> Fix that logins are not case-insensitive anymore

- public/js/icinga/loader.js
This header is only used in case the response includes
multipart content. It's meant to provide a new query
string that replaces the one of the targeted container
and the resulting change also replaces the current
history entry.
> Allow multipart updates rewrite the query string

- library/Icinga/Application/Web.php
- library/Icinga/Chart/Primitive/Text.php
- modules/monitoring/application/forms/Command/Object/AcknowledgeProblemCommandForm.php
- modules/monitoring/application/forms/Command/Object/AddCommentCommandForm.php
- modules/monitoring/application/forms/Command/Object/ScheduleServiceDowntimeCommandForm.php
- modules/monitoring/application/forms/Command/Object/SendCustomNotificationCommandForm.php
- modules/monitoring/application/locale/ar_SA/LC_MESSAGES/monitoring.po
- modules/monitoring/application/locale/de_DE/LC_MESSAGES/monitoring.po
- modules/monitoring/application/locale/it_IT/LC_MESSAGES/monitoring.po
- modules/monitoring/application/locale/ja_JP/LC_MESSAGES/monitoring.po
- modules/monitoring/application/locale/pt_BR/LC_MESSAGES/monitoring.po
- modules/monitoring/application/locale/ru_RU/LC_MESSAGES/monitoring.po
- modules/monitoring/application/locale/uk_UA/LC_MESSAGES/monitoring.po
- modules/translation/doc/03-Translation.md
Remove consecutive occurrences of 'the'
`s/the the /the /g`
> Fix typos: consecutive use of 'the'

- application/clicommands/ModuleCommand.php
- application/controllers/AboutController.php
- application/controllers/ConfigController.php
- application/controllers/ErrorController.php
- application/views/scripts/about/index.phtml
- application/views/scripts/config/module.phtml
- application/views/scripts/error/error.phtml
- icingaweb2.ruleset.xml
- library/Icinga/Application/ApplicationBootstrap.php
- library/Icinga/Application/Cli.php
- library/Icinga/Application/EmbeddedWeb.php
- library/Icinga/Application/Libraries.php
- library/Icinga/Application/Libraries/Library.php
- library/Icinga/Application/Modules/Manager.php
- library/Icinga/Application/Modules/Module.php
- library/Icinga/Application/StaticWeb.php
- library/Icinga/Application/Web.php
- library/Icinga/Application/webrouter.php
- library/Icinga/Web/Controller/StaticController.php
- library/Icinga/Web/JavaScript.php
- library/Icinga/Web/StyleSheet.php
- modules/setup/library/Setup/Utils/EnableModuleStep.php
- public/css/icinga/about.less
- public/css/icinga/main.less
- public/js/define.js
* A library is a composer `project` which is independent from other libraries and thus provides all requirements by itself
* A composer `library` is **not** a library in this case as it doesn't ship its own dependencies and is not supported
* Its name must be part of `composer.json` (Hence the name of the directory on disk is not significant)
* Its version must be part of `composer.json` or alternatively to be found in `VERSION`
* It must provide its own autoloader in `vendor/autoload.php` if it wants to provide PHP
* CSS, JS and static assets need to be placed in `asset/css`, `asset/js` and `asset/static` respectively
* Libraries are searched in paths provided by the environment variable `ICINGAWEB_LIBDIR`
* Multiple paths need to be separated by colon
* If it doesn't exist, the default …
> Add library support

- modules/monitoring/library/Monitoring/Web/Navigation/Renderer/BackendAvailabilityNavigationItemRenderer.php
We mistakenly disabled active checks in our Icinga environment and did
not notice for some time. This commit hooks into the badge mechanic used
when notifications are turned off, and also provides beads when active
host checks and active service checks are disabled.
> Add notification beads for disabled active checks

- library/Icinga/Web/Url.php
**The bug**
The self created navigation URL was displayed in plain text as you can see on the screenshot.
**Why this happend?**
This happened because the url was not escaped correctly for html special characters and if there was a special character in the url, it was displayed as plain text.
We have fixed this bug and also made changes in other places where such behavior might occur.
> Shared navigation url bug

- public/js/icinga/history.js
Without this, any subsequent call to `pushCurrentState()` has no effect in case the same url is used that was replaced.
> history.js: Set `lastPushUrl` in method `replaceCurrentState()`

- public/js/icinga/loader.js
This has previously not been an issue, as form submits seem to have
never targeted another url than their container's current one.
Though any form that did this, was pushed to history upon submit.
This happens now only for `GET` forms.
> Don't add form submits other than `GET`s to the history

- application/controllers/ApplicationStateController.php
- library/Icinga/Web/Controller/ActionController.php
We can't change its interface because the Director [overrides it](https://github.com/Icinga/icingaweb2-module-director/blob/master/library/Director/Web/Controller/ActionController.php#L132-L143) to accomplish something that could have also been patched into Icinga Web 2, but nvm..
The alternative solution for controllers not wanting to be subjected to the user's preferences is the one proposed here. Though, it requires to bypass the setter, of which I'm not a huge fan of. Though, it's the only *not-awkward* (without an over-complicated interface) solution I have.
I'm open for other alternatives.
> Drop new parameter from ActionController::setAutorefreshInterval()

- library/Icinga/Web/Response.php
If compact layout has been requested (`View::$compact === true`), `showCompact=1` is now automatically added to the target url.
This is based on the assumption that a request that is expected to return compact content, should do so even in case of a redirect. Without the client having to detect the redirect and re-request compact content. I also made this part of `Response` as handling this parameter (in this way) shouldn't be part of a module, but the framework itself.
refs #4164
fixes Icinga/icingadb-web#125
> Automatically preserve showCompact parameter when redirecting

- icingaweb2.ruleset.xml
- library/Icinga/Util/LessParser.php
- library/Icinga/Web/LessCompiler.php
Since the latest update of lessphp the compiler spit out fatal errors if it encountered missing variables or mixins. We accepted this because these are errors/bugs after all.
Though since we added support for libraries in #4271 we may face a bigger problem with this. A library may depend on a variable or even a mixin and if that's missing, katsching. This can always happen and even might not be due to a configuration error or forgotten installation.
Just consider a module that requires a library for which it has to provide a specific variable to initialize it correctly. And what happens if the user installs said library and tries to enable the module using the UI? Correct, katsching. (Though, only if there's no cache hit, but anyway..)
This PR now provides a subclass of `lessc` which only …
> Do not abort LESS compilation due to missing variables and mixins

- application/controllers/AccountController.php
- application/controllers/AnnouncementsController.php
- application/controllers/ConfigController.php
- application/controllers/GroupController.php
- application/controllers/NavigationController.php
- application/controllers/RoleController.php
- application/controllers/UserController.php
- application/controllers/UsergroupbackendController.php
- application/forms/Navigation/NavigationConfigForm.php
- application/forms/PreferenceForm.php
- application/forms/Security/RoleForm.php
- application/views/scripts/announcements/index.phtml
- application/views/scripts/config/userbackend/reorder.phtml
- application/views/scripts/group/list.phtml
- application/views/scripts/group/show.phtml
- application/views/scripts/role/list.phtml
- application/views/scripts/user/list.phtml
- application/views/scripts/user/show.phtml
- doc/06-Security.md
- library/Icinga/Application/Web.php
- library/Icinga/Authentication/AdmissionLoader.php
- library/Icinga/Authentication/Role.php
- library/Icinga/Authentication/RolesConfig.php
- library/Icinga/User.php
- library/Icinga/Web/Menu.php
- modules/monitoring/application/controllers/ConfigController.php
- public/css/icinga/widgets.less
- test/php/library/Icinga/UserTest.php
- test/php/library/Icinga/Web/Widget/SearchDashboardTest.php
Supplements https://github.com/Icinga/icingadb-web/pull/158 and adds the following features:
* **Role refusals**
The picture below shows that all command permissions are granted. Though, not those to add or remove comments.
* **Role inheritance**
No picture. This has only an effect behind the scenes. Single inheritance only. No special behavior, memberships are just shared between roles this way.
* **Unrestricted Roles**
A new option in addition to `Administrative Access`. If enabled, this causes the restrictions of the role and any other one to be ignored.
* **Password changes not allowed by default anymore**
The fake refusal `no-user/password-change` has now been changed to a grant `user/password-change`. Any user that had `no-user/password-change` previously still cannot change …
> Authorization enhancements

- library/Icinga/Web/Form.php
- modules/monitoring/application/forms/Command/Object/CheckNowCommandForm.php
... otherwise Form#handleRequest() bypasses Form#isSubmitted()
on API requests and considers the CheckNowCommandForm submitted.
fixes #4281
> CheckNowCommandForm#init(): set submit label

- library/Icinga/Web/Widget/FilterEditor.php
> Don't double encode query param values when using the quick search

- application/forms/Security/RoleForm.php
- public/css/icinga/widgets.less
> RoleForm: Highlight set privileges in headers

- library/vendor/JShrink/Minifier.php
- library/vendor/JShrink/SOURCE
As mentioned in https://github.com/Icinga/icingaweb2/pull/4289#issuecomment-747896920, JShrink needs to be updated for PHP 8 as well.
Because there is no release with those changes yet, a commit ref is used as version.
> Update JShrink for PHP 8 support.

- modules/monitoring/application/controllers/EventController.php
- modules/monitoring/library/Monitoring/Hook/EventDetailsExtensionHook.php
Hello, this is our proposed bugfix for the bug https://github.com/Icinga/icingaweb2/issues/4370
fixes #4370
> Pass event instead of object to the getHtmlForEvent method of EventDetailsExtensionHook

- application/controllers/ConfigController.php
- library/Icinga/Web/JavaScript.php
- library/Icinga/Web/StyleSheet.php
- public/js/icinga/ui.js
We reload JS (HTTP redirect) and CSS on several occasions now:
* Upon login
* CSS is reloaded if the theme changes
* An HTTP redirect is made, if the locale changes
* Upon saving preferences
* CSS is reloaded if the theme changes
* An HTTP redirect is made, if the locale changes
* Upon en-/disabling a module
* An HTTP redirect is made
If CSS is reloaded only, it also results in a bypass of our own caching implementation.
This PR changes the following:
* Upon login
* Nothing
* Upon saving preferences
* Nothing
* Upon en-/disabling a module
* CSS is reloaded, if the module has CSS but no JS
* An HTTP redirect is made, if the module has JS
If CSS is reloaded only, it won't bypass our own caching implementation. It's mature enough now that we can safely assume new CSS/JS is delivered if …
> Improve cache handling

- modules/monitoring/application/forms/Command/Object/ScheduleHostDowntimeCommandForm.php
- modules/monitoring/application/forms/Command/Object/ScheduleServiceDowntimeCommandForm.php
- modules/monitoring/doc/03-Configuration.md
[hostdowntime_end_fixed], [hostdowntime_end_flexible], [hostdowntime_flexible_duration], [servicedowntime_end_fixed], [servicedwontime_end_flexible],
[servicedowntime_flexible_duration] and [comment_text] options added to [settings] section in config.ini file used in  host/service downtime dialog.
resolves #4364
> Add end time and comment options to settings section for host/service downtime dialog

- modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php
```
object Host "host_without_service" {
display_name = "Host Without Service"
check_command = "dummy"
check_interval = 10m
retry_interval = 10m
vars.dummy_state = 2
vars.issue_no = 4404
vars.teams = [ "4404-test" ]
}
object Host "host_with_ungrouped_service" {
display_name = "Host With Ungrouped Service"
check_command = "dummy"
check_interval = 10m
retry_interval = 10m
vars.dummy_state = 0
vars.issue_no = 4404
vars.teams = [ "4404-test" ]
}
object Host "host_with_grouped_service" {
display_name = "Host With Grouped Service"
check_command = "dummy"
check_interval = 10m
retry_interval = 10m
vars.dummy_state = 0
vars.issue_no = 4404
vars.teams = [ "4404-test" ]
}
object HostGroup "4404-test" {
display_name = "4404 Test"
assign where "4404-test" in host.vars.teams
}
object Host …
```
> Fix group views not showing all objects with mixed group filters

- doc/80-Upgrading.md
On my system (Ubuntu Server 20.04.2 LTS) the schema upgrade scripts were not at `/usr/share/doc/icingaweb2/schema/*-upgrades/` (a `schema` directory didn't even exist at this location) but at `/usr/share/icingaweb2/etc/schema/*-upgrades/`.
> [Docs] Add path to database schema update scripts for Debian/Ubuntu

- public/js/icinga/behavior/datetime-picker.js
* has a native `datetime-local` input. Uses 24h format for e.g. German, otherwise 12h format. But the date format is always mm/dd/yyyy.
* has a native `date` input. Uses always mm/dd/yyyy format.
* has a native `time` input. Uses 24h format for e.g. German, otherwise 12h format.
* falls back to `text` for `datetime-local` inputs.
* has a native `date` input. Uses a locale aware format.
* has a native `time` input. Uses 24h format for e.g. German, otherwise 12h format.
* has a native `datetime-local` input. But there's only a date picker, time needs to be entered by keyboard.
* ?
* ?
We show the Flatpickr only in Firefox for `datetime-local` inputs. Otherwise we'll leave the browser's native input alone.
We should really consider to switch from `datetime-local` to a combination of `date` …
> Only use Flatpickr for non-native inputs

- modules/monitoring/application/forms/Command/Object/ScheduleHostDowntimeCommandForm.php
- modules/monitoring/library/Monitoring/Command/Object/ApiScheduleHostDowntimeCommand.php
- modules/monitoring/library/Monitoring/Command/Object/ScheduleHostDowntimeCommand.php
- modules/monitoring/library/Monitoring/Command/Renderer/IcingaApiCommandRenderer.php
Since Icinga 2.11.0 the schedule-downtime API supports the
all_services parameter. So far we've always sent a separate
request for scheduling service downtimes. As of Icinga 2.13.0,
these service downtimes are automatically removed when the host
downtimes are removed. Of course, this doesn't work if we don't
use the all_services parameter but send a separate request.
With this commit we set this parameter if the transport is API
and Icinga is equal to or greater than 2.11.0.
In addition, if child_options and all_services were previously set,
a request was sent per host and service. This is now also only a
single request if an API command transport is requested or only
API command transports are configured.
> If appropriate, set the API parameter all_services for schedule-downtime

- library/Icinga/Data/Filter/FilterEqual.php
- library/Icinga/Data/Filter/FilterEqualOrGreaterThan.php
- library/Icinga/Data/Filter/FilterEqualOrLessThan.php
- library/Icinga/Data/Filter/FilterLessThan.php
When the column is not set for the filters undefined property exception is thrown in icinga-director. This is a quick fix to solve the issue.
fixes icinga/icingaweb2-module-director#1795
> Check if the column in the row is set for filters

- .puppet/profiles/icingaweb2_dev/manifests/init.pp
... to avoid failures due to Composer platform checks.
> Vagrant: Puppet: icingaweb2_dev: don't let icingacli run on PHP 5.4

- library/Icinga/Application/Libraries/Library.php
Non javascript files in asset/js folder or non css or less files in asset/css folder causes minfier to throw error. This is handled here.
fix #4519
> Handle non `.js` files in asset/js and non `.css` or `.less` in asset/css folder

- public/css/icinga/widgets.less
Removes the margin from the `p` element.
Before
After
> CSS: Optimize notifications layout

- public/css/icinga/tabs.less
In host group detail view the tab dropdown is obscured by the .object-statistics-total of the detail header. This changes fixes this.
> tabs.less: Fix tab dropdown being obscured by object-statistics-total

- public/js/icinga.js
- public/js/icinga/events.js
- public/js/icinga/loader.js
When any view includes a sub-container of this form, the required JS code might not be loaded:
<div class="icinga-module module-dummy" data-icinga-module="dummy">...</div>
This can happen for most hooks, e.g. DetailView or Perfdata.
Introduced by 48098a2830e8dce86ae7f0e1449981c88008a7e0
I also slightly refactored the module loading calls.
> js: Fix regression for loading dependent modules for sub-containers

- public/css/icinga/base.less
Smaller fix for `pre` elements
> base.less: Optmize contrast for `pre` elements

- public/js/icinga/behavior/modal.js
- public/js/icinga/events.js
In safari, the submit buttons in filter modal window of icingadb module were unresponsive, this is fixed here.
> Fix unresponsive modal submit buttons in Safari

- library/Icinga/Web/StyleSheet.php
fixes #4635
closes https://github.com/Icinga/icingaweb2-module-reporting/issues/106
> StyleSheet: Use an absolute path to load responsive login orbs

- public/css/icinga/mixins.less
To make ipl-web independent, all mixins used in ipl-web are now
defined in ipl-web (https://github.com/Icinga/ipl-web/pull/54).
Therefore, these mixins are redundant here.
Merge this branch after the https://github.com/Icinga/ipl-web/pull/54 has been merged.
> Remove mixins that exist in ipl-web

- modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
Not easy to explain what this fixes. Check out https://github.com/Icinga/icingaweb2-module-cube/commit/14fda58ef2c3431a1ce017a91d9123b260c670e2, have a restriction or filter for `service_description` on the hosts view and this appears:
```
Undefined array key 0
#0 /icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(623): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer)
#1 /icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(673): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->createSubQueryFilter(Object(Icinga\Data\Filter\FilterExpression), String)
#2 /icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(753): …
```
> IdoQuery: Don't try to add a `HAVING` without group by rules

- public/css/icinga/about.less
Makes it more consistently obvious, that "configure" links are interactive.
> about.less: color “configure” links in about view

- modules/monitoring/application/views/scripts/partials/object/detail-content.phtml
- modules/monitoring/application/views/scripts/show/components/customvars.phtml
- modules/monitoring/library/Monitoring/Hook/CustomVarRendererHook.php
- modules/monitoring/library/Monitoring/Web/Widget/CustomVarTable.php
- modules/monitoring/public/css/module.less
> Custom variable rendering hooks

- application/forms/PreferenceForm.php
if  global theme is selected and theme chooser is disabled, ther should be a check on the system default theme which is the selected theme, if there is dark/lightmode support.
fixes #4723
> Fix missing global theme check refs #4723

- library/Icinga/Authentication/Auth.php
> Correct Auth#getUser() type spec

- library/Icinga/Data/Filter/FilterChain.php
Due to instantiation of filters using Filter::matchAll() in ObjectList::getFilter(), we get an empty FilterAnd instance when
$this->filter is null. This prepends unnecessary separator '&' to the query string during conversion of filter to querystring.
This breaks the state badge links for host and service lists int host/service detail view when multiple hosts or services are selected.
fix #4751
> Prevent use of empty filters in FilterChain::toQueryString()

- public/js/icinga/behavior/modal.js
Fixes a bug that when e.g. closing a color picker by clicking the escape key,
also the `modal.hide()` action is performed, even though there was no real modal
opened before, but it seems to react automatically on the escape key click.
> modal.js: Fix modal hide error

- library/Icinga/Web/Controller/ActionController.php
`postDispatchXhr()` also only overrides them if enabled.
> ActionController: Don't override reload rules in `redirectXhr()`

- public/js/icinga/loader.js
Direct access (a.href) automatically prepends the scheme and hostname.
fixes #4754
> Fix: Scheme and hostname prepended to col2 url in the address bar

- library/Icinga/Data/Db/DbConnection.php
- modules/monitoring/application/controllers/ShowController.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/CommentQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/CommentdeletionhistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/CommenthistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/ContactQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/CustomvarQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/DowntimeQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/DowntimeendhistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/DowntimestarthistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/EventhistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/FlappingstarthistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatussummaryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/NotificationQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/NotificationhistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatussummaryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/StatehistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/StatussummaryQuery.php
- modules/monitoring/library/Monitoring/DataView/DataView.php
- modules/monitoring/library/Monitoring/Object/Host.php
- modules/monitoring/library/Monitoring/Object/MonitoredObject.php
- modules/monitoring/library/Monitoring/Object/Service.php
Correspondingly the rendering of the filter for the db query is also modified to identify the instances of FilterEqual and to render accordingly.
This correctly selects the host, service or contact for the detailed view in case the object name contains wild card characters like "\\*".
depends on #4758
fix #4682
> Change FilterMatch to FilterEqual class for single object filter on object name.

- library/Icinga/Common/PdfExport.php
> PdfExport: Show decoded url in pdf footer

- public/css/icinga/layout-structure.less
As `#header` only contains announcements, It should not be hidden in the `fullscreen-layout`.
fixes #4596
> Display announcements in fullscreen-layout

- modules/monitoring/library/Monitoring/Object/MonitoredObject.php
A call to `__get()` reset the `customvarsWithOriginalNames` array if the given `$name` is a customvar.
If `service` has a `host` customvar filter, the `fetchHostVariables()`
method was executed and overwrote the `customvarsWithOriginalNames` array.
fixes #4757
> overrides `customvarsWithOriginalNames` only if the given object is of type `host`

- library/Icinga/Web/StyleSheet.php
must be backported to 2.9.7 and 2.10.2
> Stylesheet: Don't parse library CSS as LESS

- public/js/icinga/history.js
- public/js/icinga/ui.js
This is required so that attributes like `data-icinga-container-id` are properly managed if the user navigates using the history buttons. Previously these were not managed at all as `applyLocationBar` didn't made use of ui.js' capabilities to paste/cut/move contents.
I've rewritten `applyLocationBar` basically. It now also just moves a column if only the location has changed, not the url.
I will add a comment with test-cases the next days.
> history.js: Properly handle data attributes upon navigation

- public/js/icinga/loader.js
Search requests are handled elsewhere in a more dynamic way since .. some time. This part also used to be active only in case Icinga Web is hosted at the root of the web server, which many users don't do as otherwise we would have gotten more reports in the past regarding the reload animation. Or rather, about the 
login not working due to the same reason.
It's gone for good now.
fixes #4834
> Remove legacy search request handling

- library/Icinga/Less/Call.php
- library/Icinga/Less/ColorProp.php
- library/Icinga/Less/ColorPropOrVariable.php
- library/Icinga/Less/DeferredColorProp.php
- library/Icinga/Less/LightMode.php
- library/Icinga/Less/LightModeCall.php
- library/Icinga/Less/LightModeDefinition.php
- library/Icinga/Less/LightModeTrait.php
- library/Icinga/Less/LightModeVisitor.php
- library/Icinga/Less/Visitor.php
- test/php/library/Icinga/Util/LessParserTest.php
Currently, if a variable is pointing to another variable, which in turn is pointing to another variable, e.g. `@foo: green; @foo-bar: @foo; @foo-bar-foo: @foo-bar;` and when the variable `@foo-bar-foo` is used somewhere, the resolution of the variable hierarchy is not performed as defined. The resolved version of this variable would look like `var(--foo-bar-foo, green)`, which is actually wrong. This is because all variables in between will simply omitted and results in the following behavior. Suppose that the variable `@foo: green` is a base variable of Icinga Web 2 and has an appropriate light mode rule defined for it and changes the value to `--foo: white;`. But since the variable hierarchy is not taken into account, the parser will never notice that the value of the base variable has …
> Fix light mode variable references resolution issue

- modules/monitoring/application/views/scripts/show/components/downtime.phtml
Case: there are no comments, one downtime and you may not schedule additional ones.
Before: downtime is not shown in checkable detail view.
After: downtime is shown in checkable detail view.
Found while working on ref/IP/42380 .
> Unveil hidden downtime in checkable detail view

- library/Icinga/Protocol/Ldap/LdapConnection.php
Previously, with PHP 7.3+, the cookie value was neither read from the response nor updated on the subsequent requests.
Please note that this commit changes the parameters of the public function `LdapConnection::ldapSearch()`, but at least in our ecosystem, `LdapConnection` is the only consumer of this function. I choose not to try to keep this backward compatible and just break the API.
With PHP 7.3+, the server-side sorting control is now passed directly to the requests as well.
fixes #4900 
fixes Icinga/icingaweb2-module-director#2574
> Fix LDAP pagination for PHP7.3+

- public/css/icinga/forms.less
I don't quite understand why exactly this rule exposes such an issue. We have several other rules that are similar. But they don't reference form elements on the left. I suspect a different issue somewhere else, this only exaggerated it.
fixes #4929
> css: Optimize performance

- library/Icinga/Cli/Documentation/CommentParser.php
Well, what should I say, the PHP code sniffer allows us up to `120` characters line length and when you code/format based on these rules, e.g the description of a cli command, it will mess everything up when you run `icingacli module --help`. So if we are allowed to have up to 120 characters on a line in the code, why not in the output.
> CommentParser: Wrap outputs after `120` chars and not `72`

- application/forms/Config/Resource/SshResourceForm.php
in the tooltip of the message shown instead of the private key.
fixes #4947
> SshResourceForm: fix XSS by escaping user-defined resource name

- public/js/icinga/behavior/form.js
A while ago this already has changed so that autosubmit responses are guaranteed to be applied. Thus this
exception is now obsolete.
fixes #4942
> form.js: Don't ignore autosubmit elements

- library/Icinga/Less/Visitor.php
- public/css/icinga/print.less
- test/php/library/Icinga/Util/LessParserTest.php
> Fix browser print dialog result

- public/js/icinga/behavior/modal.js
- public/js/icinga/loader.js
Previously all `input` elements (text, date, number, ...) got also disabled. This is unecessary.
> js: Only disable submit buttons on form submit

- library/Icinga/Application/Libraries.php
> Libraries: Only attempt a partial match if the library name contains a slash

- modules/setup/library/Setup/Webserver.php
- modules/setup/library/Setup/Webserver/Apache.php
if the Alias URI (e.g. /) has a trailing /. Otherwise Apache says 403.
* `RUN ["icingacli", "setup", "config", "webserver", "apache", "--path=/icingaweb2", "--file=/etc/apache2/conf-enabled/icingaweb2.conf"]` still works es expected
* `RUN ["icingacli", "setup", "config", "webserver", "apache", "--path=/", "--file=/etc/apache2/conf-enabled/icingaweb2.conf"]` now works es expected
This would allow me to remove the `--root=/usr/share/icingaweb2/public/` workaround from Icinga/docker-icingaweb2#105.
> icingacli setup config webserver apache: add trailing / to Alias dir

- public/js/icinga/loader.js
Although Icinga Web itself doesn't allow scrolling along the y-axis, there may be modules that do. So far we've only kept scrolling position on the x-axis. Now we also support preserving the scrolling position along the y-axis. `requestAnimationFrame()` is used in order to prevent flickering.
> js: Also preserve scroll-y upon auto-refresh

- library/Icinga/Exception/IcingaException.php
If the passed message contains a `%`, but no `$args`, `vsprintf()` throws an error.
fixes: #5004
> IcingaException: Only use `vsprintf()` if `$args` given

- modules/monitoring/library/Monitoring/Timeline/TimeLine.php
Php < 8.1 converts fetched time(stamp) to string. This must always be an int.
fixes #5025
> TimeLine: Always parse `int` to validateTime()

- modules/monitoring/library/Monitoring/Web/Navigation/Renderer/MonitoringBadgeNavigationItemRenderer.php
Summary badges are failing in case one of your roles has a wildcard filter:
> MonitoringBadgeNavigationItemRenderer: do not fail

- public/js/icinga/behavior/modal.js
- public/js/icinga/loader.js
* Let response header `X-Icinga-Container` either influence a request's `$target` or `$redirectTarget`, but not both
* Issuing a `__CLOSE__` in a detail url still closes `#col2` and refreshes `#col1`
* Issuing a `__CLOSE__` for a nested container still empties it
* Issuing a `__CLOSE__` in a modal, now refreshes the modal openers container (now also `#col1`)
> js: Enhance server side container closing

- public/js/icinga/loader.js
When sending extra updates using the `X-Icinga-Extra-Updates` header, the values are processed differently given a single and multiple `key=>value` containers. When sending a single additional update, the container ID is expected to be specified like `#col1` or `.container`, but for `container=>url` pairs, the container ID is required to be provided without `#`: `['col2' => '__CLOSE__']`.
With this PR both variants are supported.
> loader.js: Fix extra updates values inconsistency

- application/controllers/ConfigController.php
- application/forms/Config/General/ApplicationConfigForm.php
- doc/03-Configuration.md
- doc/20-Advanced-Topics.md
- library/Icinga/Util/Csp.php
- library/Icinga/Web/Controller/ActionController.php
- library/Icinga/Web/Response.php
> Content Security Policy ([CSP](https://developer.mozilla.org/en-US/docs/Glossary/CSP)) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross-Site Scripting ([XSS](https://developer.mozilla.org/en-US/docs/Glossary/Cross-site_scripting)) and data injection attacks. These attacks are used for everything from data theft, to site defacement, to malware distribution.
([MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP))
This PR allows to enable strict CSP by introducing the following features:
* A setting to enable strict CSP in the application configuration.
* A helper class for setting/recreating/accessing nonces for dynamic CSS persisted in window-aware sessions, and for generating the CSP header.
* Logic in our base …
> Allow Enabling Strict Content Security Policy (CSP)

- public/js/icinga/loader.js
A redirect now also does NOT:
* Remove `.impact` from the container
* Try to set a menu item active..
fixes #4879
> loader.js: Don't update history for redirects

- public/css/icinga/main.less
In Chrome the marker was already invisible since normalize.css applies `display:block` to `summary`. Hence we should also disable the marker by default in Safari.
fixes https://github.com/Icinga/icingaweb2-module-businessprocess/issues/406
> css: Hide details marker of collapsibles in Safari

- application/forms/Config/Resource/DbResourceForm.php
- library/Icinga/Application/Platform.php
`oci` uses Zend's `Oracle` adapter, which does not use this setting at all.
fixes #5062
> Make `host` optional for `oci` database resources

- .github/workflows/docker.yml
Just like in all other repos making Docker images.
The following tasks finish our ARM support and depend on each other:
Deriving X.Y from X.Y.Z is easy. Nobody releases a vX.Y.Z and a vX.Y.{Z+1} at the same time. But a vX.Y.Z and a vX.{Y+1}.0 is likely. Both check Docker Hub, both get green light and both push :latest. Who wins?
> Release GHA: create only one Docker image at the same time

- application/controllers/StaticController.php
- modules/monitoring/application/views/scripts/show/contact.phtml
- phpstan-baseline.neon
The gravatar for contacts was never correctly rendered in the detailed page. Hence it will be completely removed.
ref #5089
> Remove redundant gravatar in contact detail

- library/Icinga/Web/Response.php
If the redirect target changes, `__CLOSE__` has no effect
fixes #5081
> Response: Fix backwards compatibilty for `__CLOSE__`

- modules/monitoring/library/Monitoring/ProvidedHook/X509/Sni.php
To avoid such crashes:
```php
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Db/Adapter/Pdo/Abstract.php(265): Zend_Db_Adapter_Abstract->query('SELECT ho.name1...', Array) …
```
> X509\Sni: Clear backend instances before performing actual DB queries

- library/Icinga/Application/Hook/DbMigrationHook.php
Testing the migration hook with PHP 7.2, 7.3 renders the following stack trace.
```php
Undefined offset: 3
#0 /icingaweb2/library/Icinga/Application/Hook/DbMigrationHook.php(308): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /icingaweb2/library/Icinga/Application/Hook/DbMigrationHook.php(172): Icinga\Application\Hook\DbMigrationHook->load()
...
```
> DbMigrationHook: Pad matching groups to the desired length before using them

- library/Icinga/Web/Controller/ActionController.php
This ensures that, if CSP is enabled, the newly created token on the login is accepted by the browser. A small, but IMHO desired, side effect is that the login now always appears in the default theme.
fixes #5126
> Always reload window when redirecting to the login

- library/Icinga/Application/MigrationManager.php
- modules/setup/application/forms/DbResourcePage.php
- modules/setup/library/Setup/Utils/DbTool.php
- modules/setup/library/Setup/WebWizard.php
- phpstan-baseline.neon
> Fix `PostgreSQL` grants

- library/Icinga/Web/Response.php
- public/js/icinga/loader.js
> Fix redirection loop

- .github/workflows/php.yml
- library/Icinga/Protocol/Ldap/LdapConnection.php
This is deprecated since PHP 8.3.
But this is unnecessary anyway as the passed hostname is computed by #normalizeHostname() which takes the port into account.
fixes #5136
Now, in contrast to that issue, adding an LDAP resource doesn't print a PHP deprecation notice.
> LdapConnection#prepareNewConnection(): don't pass the port to ldap_connect()

- RELEASE.md
Our GHA are going to create all Docker tags by themselves, no manual action needed.
@julianbrost As you wanted. (https://github.com/Icinga/docker-icingaweb2/pull/104#issuecomment-1750280086)
> RELEASE.md: remove obsolete Docker section

- modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimeendhistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimestarthistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimeendhistoryQuery.php
- modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimestarthistoryQuery.php
fixes https://github.com/Icinga/icingaweb2/issues/5176
> add canceled downtimes to the history, if they were started

- library/Icinga/Protocol/Ldap/LdapConnection.php
fixes https://github.com/Icinga/icingaweb2/issues/5202
> LdapConnection: Access array key only if its set

- modules/setup/application/forms/DbResourcePage.php
> DbResourcePage: Warn the user if Icinga DB is used as configuration database

- modules/monitoring/public/css/tables.less
- public/css/icinga/main.less
The `.active` state should not be overwritten by `:hover`.
> Css: Do not allow `:hover` to affect the `.active` list elements

- doc/20-Advanced-Topics.md
Hi, 
I updated the docs for the Content Security Policy (CSP). The Director was missing from the list.
Was implemented in https://github.com/Icinga/icingaweb2-module-director/pull/2857
Edit: I also added a hint about how to enable CSP in Icinga Web.
Cheers
Markus
> Add Icinga Director to list of components capable of strict CSP

- public/css/icinga/menu.less
- public/js/icinga/behavior/navigation.js
> Flyout menu: Render menu `bottom-up` if it exceeds the viewport height

- doc/02-Installation.md
- doc/05-Authentication.md
- doc/07-Preferences.md
as discussed in https://github.com/Icinga/icingaweb2/issues/5237
> add MariaDB to installation doc

- doc/80-Upgrading.md
- modules/monitoring/application/views/scripts/show/components/output.phtml
Concatenate Output.
This might break workarounds used implemented in a PluginOutputHookImplementation but I haven't found any out in the wild.
This removes the annoying space between the first line and the other lines in the monitoring module plugin output
Alternatives :
Introduce a monitoring setting that disables this fix for a fast switch back in case this breaks something
Best Regards
Nicolas
> Fix PluginOutputHookImplementation gets called twice #5271

- doc/20-Advanced-Topics.md
Only got the documented steps to work if the [autologin] part was added, so I suppose it is missing from this documentation
> Corrected kiosk mode config

- application/views/scripts/about/index.phtml
fixes https://github.com/Icinga/icingaweb2/issues/5236
> About Page: Suppress the MigrationManager exception

- library/Icinga/File/Csv.php
When performing a str_replace, subject should always be a string. If passing a non-existent column or empty column, subject may be null
This ensure str_replace is called when subject is actually a string (not NULL)
> fix(csv): fix #5279 always force subject to be a string in str_replace

- doc/02-Installation.md
for the same security reasons we don't use apt-key add anymore for: https://blog.cloudflare.com/dont-use-apt-key
Our repos already reference https://packages.icinga.com/icinga.key and both RPM distro families properly handle that.
* CC https://github.com/Icinga/packages.icinga.com/pull/42
> Don't rpm --import https://packages.icinga.com/icinga.key

- application/forms/Config/General/ApplicationConfigForm.php
Fix a consecutive "to" in a form element description.
> ApplicationConfigForm: fix typo

- public/css/icinga/forms.less
The height for `input[type=“datetime-local”]` ist fixed.
But I can’t reproduce the problem for `select`s
> CSS: Set correct height input[type=“datetime-local”]

- public/js/icinga/behavior/modal.js
- public/js/icinga/events.js
When there are multiple submit buttons outside the form which are associated with it as shown below, the form fails to correctly identify the pressed submit button.
```
<html>
<form id="test-form">
<input type="text" name="name"/>
<input value="Save" name="save" type="submit">
</form>
<div>
<button type="submit" form="test-form" name="button-1">Button 1</button>
<button type="submit" form="test-form" name="button-2">Button 2</button>
</div>
</html>
```
In case the button is undefined upon submit event, get the pressed submit button using the [submitter](https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter) property found on the `SubmitEvent` interface.
> Form submission: Identify pressed submit button associated through form attribute

- application/controllers/RoleController.php
- library/Icinga/Authentication/RolesConfig.php
- library/Icinga/Data/DataArray/ArrayDatasource.php
- test/php/library/Icinga/Data/DataArray/ArrayDatasourceTest.php
> Fix sort roles by name

- public/js/icinga/behavior/form.js
This slipped through, as I thought the CSS selector `:input`, which was used previously, is invalid. Although, it's a jQuery specific selector -.-, which was also previously used.
fixes #5293
> form.js: Ignore buttons again when being asked to render content

- application/views/scripts/config/module-configuration-error.phtml
- modules/monitoring/application/forms/Config/BackendConfigForm.php
In both cases the input, which wasn't escaped before, comes from a form element that doesn't allow any user to change its content. An ordinary user would need to access the DOM in order to do that.
Both forms are protected by CSRF, so this mitigates any potential exploit as well.
> Fix unescaped error messages

- modules/doc/public/css/module.less
- Replaced the gradient mixin with a simple color for odd rows. This fixes and markdown table rows in light mode and - since there are very gradients in general - it makes the overall look more uniform.
Fixes https://github.com/Icinga/icingaweb2/issues/5320
> Fix doc module markdown table rows in light mode

- public/css/icinga/tabs.less
resolves https://github.com/Icinga/icingaweb2/issues/5303
> tabs.less: Don't let icinga-loader element overlap the dropdown nav

- library/Icinga/File/Pdf.php
This is required since dompdf seems to automatically load our custom font and complains otherwise.
> Pdf: Ensure dompdf can create temporary files

- library/Icinga/Web/Menu.php
- library/Icinga/Web/Navigation/Renderer/RecursiveMenuNavigationRenderer.php
- library/Icinga/Web/Navigation/Renderer/RecursiveNavigationRenderer.php
- public/css/icinga/menu.less
Add a title to the navigation level-2 flyouts. The title is only displayed if the sidebar is collapsed.
Closes #4968
> Show title in level-2 flyouts

- modules/monitoring/application/forms/Command/Object/AcknowledgeProblemCommandForm.php
- modules/monitoring/doc/03-Configuration.md
I propose to add a new option for setting a default comment for acknowledging problems (`acknowledge_comment_text`), similar to the existing `hostdowntime_comment_text` and `servicedowntime_comment_text` options.
> Support setting a default comment for acknowledgements

- library/Icinga/Application/ApplicationBootstrap.php
- library/Icinga/Application/webrouter.php
- test/php/library/Icinga/File/Storage/LocalFileStorageTest.php
in ApplicationBootstrap#setupErrorHandling(). In webrouter.php disable them unconditionally (until ApplicationBootstrap#setupErrorHandling()) not to duplicate the check. ApplicationBootstrap#setupErrorHandling()) is called pretty early, so we won't miss much.
fixes #5117
* In addition, this provides #5269 and mitigates #5152 in production where ICINGAWEB_ENVIRONMENT isn't set.
> Disable deprecation warnings unless ICINGAWEB_ENVIRONMENT is set to "dev"

- public/js/icinga/behavior/navigation.js
> Menu navigation: Improve flyout transition

- public/css/icinga/configmenu.less
> Don't let active `.nav-level-2` menu item overlap the config nav flyout

- application/forms/MigrationForm.php
- modules/setup/application/forms/DatabaseCreationPage.php
On the migration overview, there is no way to verify that the privileges checked are for a MySQL database, as there is no access to which migration this has caused.
It looks like this:
> Warn about db name wildcards
